|****************************************************************************************************************
CataKill.mac - by Kroaking
Last Updated: April 6th, 2026 - 02:34:00 PM

v2.1.7

****************************************************************************************************************|
/squelch /log on
#chat group

#Event Catacomb_A "#*#Should you come across a dragorn known as Dragorn Marshal Greshka#*#"
#Event Catacomb_B "#*#Should you come across a noc known as Elite Overlord Vijaz#*#"
#Event Catacomb_C "#*#Should you come across a noc known as the Master of the Watch#*#"

#Event CantSee "You cannot see your target."
#Event TooFar  "Your target is #*#, get closer!"
#Event CantHit "You can't hit them from here."

#Event BagsFull "#*#There was no place to put that#*#"
#Event BagsFull "#*#There are no open slots for the held item in your inventory#*#"

#event NavMeshReload "#*#Could not locate destination on navmesh#*#"

#event TurboLootDone "#*# tells the group, '[DONE LOOTING]'#*#"

#define /message "/echo \ay[\atCataKill\ay]\aw "

| --------------------------------------------------------------------------------------------
Sub Main
	/if (${Debugging}) /echo Sub Main Entry

	/declare StuckSpamTimerSet	timer		outer	0
	/declare StuckSpamTrigger	timer		outer	0
	/declare OutX1 				int 		outer 	${Me.X}
	/declare OutY1 				int 		outer	${Me.Y}
	/declare OutZ1				int			outer	${Me.Z}
	/declare StuckCountOut 		int 		outer	0
	/declare BackUpTimer		int			outer 	0
	/declare GroupWaitTimer		int			outer	0
	/declare StuckSwitch		int 		outer
	/declare runcounter 		int 		outer	0
	/declare notkillable		int 		outer	0
	/declare Announce			bool		outer	FALSE
	/declare CurrentExpedition 	string		outer	NULL
	/declare ExpeditionDesc 	string		outer	NULL
	/declare version			string		outer	2.1.7
	/declare LastUpdated		string		outer	"Last Updated: April 6th, 2026 - 02:34:00 PM"
	
	/message ==================================================================
 	/call Declares
	/message ==================================================================
	/message \at${MacroName}.mac \aw- \atv${version} \awby \ag Kroaking
	/message \at${LastUpdated}.
	/message ==================================================================
	/delay 2s
	
	|----------------
	/call CheckThings
	|----------------	
		
	|------------------------------------------------------------------------------------------------------
	|------------
	/if (${GrpHasBRDClass}) {
		/message \ag- BRDMelodyName \ayis set to \am[\at${BRDMelodyName}\am]\ax
		/message \ag- BRDTravelSongSlot \ayis set to \am[\at${BRDTravelSongSlot}\am]\ax
	}
	|------------	
	/message \ag- CheckBots \ayis set to \am[\at${CheckBots}\am]\ax
	/message \ag- DoBurns \ayis set to \am[\at${DoBurns}\am]\ax
	/message \ag- LootCorpse \ayis set to \am[\at${LootCorpse}\am]\ax
	/message \ag- LootMethod \ayis set to \am[\at${LootMethod}\am]\ax
	/message \ag- RepeatMission \ayis set to \am[\at${RepeatMission}\am]\ax
	/message \ag- UseClickBuffs \ayis set to \am[\at${UseClickBuffs}\am]\ax
	/message \ag- UseClickDamage \ayis set to \am[\at${UseClickDamage}\am]\ax	
	
	|--------------------------------------------
	/if (${MouseLock}) {
		/message \ag- MouseLock \ayis set to \am[\at${MouseLock}\am]\ax
		/message \ag- MouseLock \aoCoordinates: \am[\atX=${MouseLocValX}, Y=${MouseLocValY}\am]\ax
		/mouseto ${MouseLocValX}, ${MouseLocValY}
	}
	|--------------------------------------------	
	
	|------------
	/if (${LootMethod.Equal[TURBOLOOT]})  {
		/message \ag- TurboLooter \ayis set to \am[\ao${TurboLooter}\am]\ax 
	}
	|------------
	
	/message ==================================================================
	
	|------------------------------------------------------------------------------------------------------
	/if (${SwarmPull}) {
		/message \ar***\at \agSwarmPull \arHigh Risk PULLING: \ayis set to \at[\ar${SwarmPull}}\at]
	} else {
		/message \ar***\at \agSwarmPull \arHigh Risk PULLING: \ayis set to \at[\ag${SwarmPull}}\at]
	}
	|------------------------------------------------------------------------------------------------------
	/if (${SwarmPull} && ${BiggerSwarms})  /message \ar***\at \agBiggerSwarms \arHigh Risk PULLING: \ayis set to \at[\ar${BiggerSwarms}\at]\ar.
	/if (${SwarmPull} && !${BiggerSwarms}) /message \ar***\at \agBiggerSwarms \arHigh Risk PULLING: \ayis set to \at[\ag${BiggerSwarms}\at]\ar.
	|------------------------------------------------------------------------------------------------------

	|-------------------------------------------------------------	
	/if ((${GrpHasENCClass} || ${GrpHasWIZClass}) && ${DoPBAOE}) {
		/message ==================================================================
		/message \ar ~ NOTE: \aoWe have \ayPBAE\ao classe(s) in group and \am[\atDoPBAOE\am]\ao is currently \am[\ar${DoPBAOE}\am]\ao.
		/message \ay ~ PBAE Mob count threshhold is currently at\ao: \am[\at${PBAOE_MobCount}\am]\ax
		/message ==================================================================	
		/delay 2s
	}
	|-------------------------------------------------------------
	
	/message ==================================================================
	/message \am- LastSwarmed_Step \ayis set to \at[\ag${LastSwarmed_Step}\at]\ax
	/message \am- CompletedPathTo \ayis set to \at[\ag${CompletedPathTo}\at]\ax
	/message ==================================================================
	/message \agGetting things ready, sit back...
	/delay 2s
	
	/message \ayI am currently in \am[\at${Zone.Name}\am]\ay.\ax
	|--------------
	/call GroupWait
	|--------------

	|----------------------
	/if (!${Select[${Zone.ID},152,202,386,336,330]}) {
		/message \ayLooks like we are \am[\atnot in a valid starting zone\am]\ay for ${MacroName} zone routing.\ax
		/call GoToMarrs
	}
	|----------------------
	
	|----------------------
 	/if (${startZone}==${Nexus}) /call GoToDranikFromNexus
	|----------------------

	|----------------------
 	/if (${startZone}==${PlaneofKnowledge}) /call GoToDranikFromPoK
	|----------------------

	|----------------------
 	/if (${startZone}==${TempleofMarr}) /call GoToDranikFromMarr
	|----------------------

	|------------------------------------------------------------------------------
	/if (${startZone}==${RuinedCityofDranik}) {
		/call GetExpeditionData
		|-------------------
		/if (${DranikCExpedition}==1) {
			/message ==================================================================
			/message \ag+\ay I currently \agHAVE\ay an expedition assigned to me - \am[\at${CurrentExpedition}\am].\ax
			/message ==================================================================
			/call GroupWait
			/call GoToExpedition
		} else {
			/message ==================================================================
			/message \ar-\ay I currently \arDO NOT HAVE\ay an expedition assigned to me !
			/message \ayI am headed to \am[\atGrand Historian Rygua\am]\ay to get an expedition.\ax
			/message ==================================================================
			/call GroupWait
			/call GotoRecruiter
		}
		|-------------------
	}
	|------------------------------------------------------------------------------

	| --- MAIN ------------------------------------------------------------------------------
	:mainloop	
	|---------
	/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) /call DoClearTargets
	|---------
	
	|--------------------------------------------
	|----------------------	 IF IN CATACOMB-C
	|--------------------------------------------
	/if (${Zone.ID}==${CataCombC}) {
		/if (${Me.XTarget}) /call DoClearTargets
		/message \ayI am currently in \am[\atCatacombs of Dranik (Caza)\am]\ay.\ax

		|----------------------------
		| ENGINE SELECT -- START
		|----------------------------
		|---- SwarmPull ----
		|----------------------------
		/if (${SwarmPull})  {
			/message ==================================================================
			/message \atCataKill \aw<\ar*\ao*\ay*\ag*\at*\au*\am*\ap*\aw> \ayABOUT TO: - \arSWARM PULL\ay . . . get ready! \aw<\ap*\am*\au*\at*\ag*\ay*\ao*\ar*\aw>
			/popcustom 13 5 ---> ABOUT TO SWARM PULL . . . get ready! <---
			/message ==================================================================
			/delay 3s
			|-----------------------------------
			| -- Call check mission zone.
			|-----------------------------------
			/if (!${Me.Combat} && !${Me.XTarget}) /call CheckExpeditionStatus
			|-------------------------While
			/while (${InADungeon}==1) && ${DranikCExpedition}==1) {
				/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) /call DoClearTargets
				/if (${LootCorpse} && !${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /call CheckForCorpses
				|------------------------------------------
				/if (!${CompletedPathTo}) {
					/call DoSwarmPull_PathTo
				} else {
					|------------------------------------------------------
					/if (!${BiggerSwarms}) {
						/call DoSwarmPull_MainLoop
					} else {
						/call DoSwarmPull_MainLoop_Bigger
					}
					|------------------------------------------------------
				}
				|------------------------------------------
				/if (${Me.XTarget}) /call DoClearTargets
				/if (!${Me.Combat} && !${Me.XTarget}) /call CheckExpeditionStatus
				/call GMCheck
				/doevents
			}
			|-------------------------While
			/if (!${Me.Combat} && !${Me.XTarget}) /call CheckExpeditionStatus
		} else {
		|----------------------------
		|---- SinglePull ----
		|----------------------------
			/message ==================================================================
			/message \atCataKill \aw<\ar*\ao*\ay*\ag*\at*\au*\am*\ap*\aw> \ayABOUT TO: - \agSINGLE PULL\ay . . . get ready! \aw<\ap*\am*\au*\at*\ag*\ay*\ao*\ar*\aw>
			/popcustom 15 5 ---> ABOUT TO SINGLE PULL . . . get ready! <---
			/message ==================================================================
			/delay 3s
			/varset PullRange ${CampRadius}
			|-----------------------------------
			| -- Call check mission zone.
			|-----------------------------------
			/if (!${Me.Combat} && !${Me.XTarget}) /call CheckExpeditionStatus
			|-------------------------While
			/while (${InADungeon}==1 && ${DranikCExpedition}==1) {	
				/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) /call DoClearTargets			
				/if (${LootCorpse} && !${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /call CheckForCorpses
				/call DoSinglePull
				/if (${Me.XTarget}) /call DoClearTargets
				/if (!${Me.Combat} && !${Me.XTarget}) /call CheckExpeditionStatus
				/call GMCheck
				/doevents
			}
			|-------------------------While
			/if (!${Me.Combat} && !${Me.XTarget}) /call CheckExpeditionStatus
		}
		|----------------------------
		| ENGINE SELECT -- END
		|----------------------------
	}
	|--------------------------------------------
	|----------------------	 IF IN CATACOMB-C
	|--------------------------------------------

	|--------------------------------------------
	|----------------------	 IF IN DRANIK
	|--------------------------------------------
	/if (${Zone.ID}==${RuinedCityofDranik}) {
		/call GetExpeditionData
		|-------------------
		/if (${DranikCExpedition}==0) {
			/message ==================================================================
			/message \ar-\ay I currently \arDO NOT HAVE\ay an expedition assigned to me !
			/message \ayI am headed to \am[\atGrand Historian Rygua\am]\ay to get an expedition.\ax
			/message ==================================================================
			/call GroupWait
			/call GotoRecruiter
		}
		|-------------------
	}
	|--------------------------------------------
	|----------------------	 IF IN DRANIK
	|--------------------------------------------
	
	/if (!${Me.Combat} && !${Me.XTarget}) /call CheckExpeditionStatus
	/doevents
	/delay 1s
	/goto :mainloop
	| --- MAIN ------------------------------------------------------------------------------
	
	/if (${Debugging}) /echo Sub Main Exit

/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: Declares
| --------------------------------------------------------------------------------------------
Sub Declares
	/if (${Debugging}) /echo Sub Declares Entry

	|==================== DO NOT ALTER THESE VALUES ====================
	/declare FarmMob 			string outer
	/declare PullRange 			int outer
	/declare MacroName			string	outer	CataKill
	/declare IniFileName		string	outer	${MacroName}_${Me.CleanName}.ini
	/declare FirstRun			int		outer	0

	|--------------------------------------
	/if (!${Ini[${IniFileName}].Length}) /varset FirstRun 1
	|--------------------------------------

	/message \ay${IniFileName} is the INI being used.
	/declare BagsAreFull		bool 	outer FALSE
	/declare CampX 				int 	outer ${Me.X}
	/declare CampY 				int 	outer ${Me.Y}
	/declare CampZ 				int 	outer ${Me.Z}
	/declare DebugRepeatTimer 	timer 	outer 1s
	/declare Endmac 			bool 	outer FALSE
	/declare PBAE_State			bool	outer FALSE
	/declare PauseForTurboloot	bool 	outer FALSE
	/declare SitDelay 			timer 	outer 5s
	/declare Targets 			string 	outer
	/declare TurboLootPause		bool	outer FALSE
	/declare courseCorrection 	timer 	outer 1s
	/declare myTargetID 		int 	outer 0
	/declare reportTarget 		timer 	outer 5s
	/declare startZone 			int 	outer ${Zone.ID}
	
	|** SPECIFIC of CataKill.mac/SwarmPull declares **|
	|----------------------------------------------------------
	/declare ZoneCount				int		outer 	0
	|----------------------------------------------------------

	|----------------------------------------------------------
	/declare InADungeon				int		outer	0
	/declare CurrentDC				int		outer	0
	/declare CurrentDCAC			int		outer	0
	/declare DranikCExpedition		int		outer	0
	|--------------------------------------
		
	|----------------------------------------------------------
	|** SPECIFIC of CataKill.mac/SwarmPull declares **|

	|** Declare colors their escape code for read-ability **|
	/declare Black 			string outer \ab
	/declare Blue   		string outer \au
	/declare Brown      	string outer \a-o
	/declare Cyan   		string outer \at
	/declare Gray			string outer \a-w
	/declare Green			string outer \ag
	/declare Pink   		string outer \am
	/declare Orange   		string outer \ao
	/declare Purple   		string outer \ap
	/declare Red   			string outer \ar
	/declare Teal   		string outer \at
	/declare White   		string outer \aw
	/declare Yellow  		string outer \ay
	/declare DarkGreen 		string outer \a-g
	/declare DarkMarroon	string outer \a-m
	/declare DarkPurple		string outer \a-p
	/declare DarkRed		string outer \a-r
	/declare DarkCyan		string outer \a-t
	/declare DarkBlue		string outer \a-u
	/declare DarkYellow		string outer \a-y
	|** End color declarations **|

	|** E3LDON.mac/PullFarm.mac type declares INIThings **|

	|** SPECIFIC of CataKill.mac/PullFarm.mac type declares **|
	/call CheckINI ${IniFileName} General Debugging bool FALSE
	/call CheckINI ${IniFileName} Camp CampRadius int 2500
	/call CheckINI ${IniFileName} Pull ZRadius int 500
	|** SPECIFIC of CataKill.mac/PullFarm.mac type declares **|

	/call CheckINI ${IniFileName} General AssistMe bool TRUE
	/call CheckINI ${IniFileName} General BiggerSwarms bool FALSE
	/call CheckINI ${IniFileName} General CheckBots bool TRUE
	/call CheckINI ${IniFileName} General DoBurns bool FALSE
	/call CheckINI ${IniFileName} General DoInvis bool TRUE
	/call CheckINI ${IniFileName} General DoPBAOE bool FALSE
	/call CheckINI ${IniFileName} General DoRogueSosCoh bool FALSE	
	/call CheckINI ${IniFileName} General GroupNavToMe bool TRUE	
	/call CheckINI ${IniFileName} General LootCorpse bool FALSE
	/call CheckINI ${IniFileName} General LootMethod string E3	
	/call CheckINI ${IniFileName} General LootTradeMats bool FALSE
	|--------------------------------------
	/if (${LootTradeMats}) {
		/declare DranikCLootArray[1,45]		outer		
	} else {
		/declare DranikCLootArray[1,37]	string	outer		
	}
	|--------------------------------------
	/call CheckINI ${IniFileName} General MouseLock bool TRUE
	/call CheckINI ${IniFileName} General MouseLocValX int 290
	/call CheckINI ${IniFileName} General MouseLocValY int 550
	/call CheckINI ${IniFileName} General PBAOE_MobCount int 5
	/call CheckINI ${IniFileName} General ReclaimDC bool FALSE
	/call CheckINI ${IniFileName} General RepeatMission bool TRUE
	/call CheckINI ${IniFileName} General SwarmPull bool FALSE
	/call CheckINI ${IniFileName} General UseClickBuffs bool FALSE
	/call CheckINI ${IniFileName} General UseClickDamage bool FALSE
	|------------------------------------------------------------
	/declare BRDTravelSong string  outer "Selo's Song of Travel"
	/call CheckINI ${IniFileName} BardSong BRDTravelSongSlot string 11
	/call CheckINI ${IniFileName} BardSong BRDMelodyName string base
	|------------------------------------------------------------
	/call CheckINI ${IniFileName} Pull PullAbility string ReplaceMeWithYourSkill
	/call CheckINI ${IniFileName} Pull PullAbilityRange int 30
	/call CheckINI ${IniFileName} Pull PullRequiresLineOfSight bool TRUE
	/call CheckINI ${IniFileName} Pull UseCastSpells bool FALSE
	|------------------------------------------------------------
	/call CheckINI ${IniFileName} Endurance MedEndAt int 8
	/call CheckINI ${IniFileName} Endurance MedEndTill int 100
	|------------------------------------------------------------
	/call CheckINI ${IniFileName} Mana MedAt int 30
	/call CheckINI ${IniFileName} Mana MedTill int 100
	/call CheckINI ${IniFileName} Mana BardMed bool TRUE
	|------------------------------------------------------------
	/call CheckINI ${IniFileName} Alerts AFKGM bool TRUE
	/call CheckINI ${IniFileName} Alerts UseBeep bool TRUE
	|------------------------------------------------------------
	/call CheckIni ${IniFileName} Theme LastSwarmed_Dungeon string NONE
	/call CheckIni ${IniFileName} Theme LastSwarmed_Step string 1
	/call CheckIni ${IniFileName} Theme CompletedPathTo bool FALSE
	|------------------------------------------------------------

	|------------------------------------------------------------------------------------------------------------
	| Set Turbolooter to the pulled variablie from Mq2Mono Query.
	|------------------------------------------------------------------------------------------------------------
	/declare TurboLooter	string	outer	${MQ2Mono.Query[e3,E3Bots(${Me.CleanName}).Query(GrpMainLooterName)]}
	|------------------------------------------------------------------------------------------------------------	

	|** End of LDON.mac/PullFarm.mac type declares **|

	|** Start ZoneID as variable **|
	/declare Nexus				int	outer 152
	/declare PlaneofKnowledge 	int outer 202
	/declare TempleofMarr 		int outer 386
	/declare RuinedCityofDranik	int outer 336
	|** Start ZoneID as variable **|

	|** Catacombs of Dranik (Caza) Zones **|
	/declare CataCombC 			int outer 330
	|** Catacombs of Dranik (Caza) Zones **|

	|** End ZoneID as Variable **|
	|==================== DO NOT ALTER THESE VALUES ====================

	|-------------------------------
	/if (${FirstRun}) {
		/message \ayCreated INI file \am[\at${IniFileName}\am]\ay with default values.\ax
		/message \ayPlease edit the file and restart \at${MacroName}.mac\ay.\ax
		/message \arEnding Macro !\ax
		/end
	} else {
		/message \ayConfig loaded from \am[\at${IniFileName}\am]\ay.\ax
	}
	|-------------------------------

	/if (${Debugging}) /echo Sub Declares Exit

/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CampInMarrs
| --------------------------------------------------------------------------------------------
Sub CampInMarrs
	/if (${Debugging}) /echo Sub CampInMarrs Entry
	/declare y int local 1
		
	/message \atWe are not set to repeat expeditions, Gating to Temple of Marr to camp !
	/message \ayI am headed to \am[\atTemple of Marr\am]\ay.\ax
	
	|---------------------
	|--- Group - GoToMarrs
	|---------------------
	/delay 10
	/squelch /e3bcgza /nav stop	
	/if (${GrpHasBRDClass}) /squelch /e3bct ${GrpBRDName} /playmelody stop
	/squelch /e3bcgza /keypress x
	/delay 6
	/squelch /e3bcgza /stand
	/delay 5
	/squelch /e3bcgza /alt act 511
	/delay 20s

	|----------------------------
	/while (${Group.Member[1].OtherZone} || ${Group.Member[2].OtherZone} || ${Group.Member[3].OtherZone} || ${Group.Member[4].OtherZone} || ${Group.Member[5].OtherZone}) {
		
		|--------------------------
		|--- Group - Start in Marrs
		|---------------------------
		/for y 1 to ${Group.Members} 
		/message \ayChecking status of: \at(\ag${Group.Member[${y}].Name}\at)\ay.
		/if (${Group.Member[${y}].OtherZone}) {
			/message \ar(${Group.Member[${y}].Name}) is NOT in ZONE !
			/squelch /e3bct ${Group.Member[${y}].Name} /nav stop
			/if (${Group.Member[${y}].Class.ShortName.Equal[BRD]}) /squelch /e3bct ${Group.Member[${y}].Name} /playmelody stop
			/squelch /e3bct ${Group.Member[${y}].Name} /keypress x
			/delay 5
			/squelch /e3bct ${Group.Member[${y}].Name} /stand
			/delay 5
			/squelch /e3bct ${Group.Member[${y}].Name} /alt act 511
			/delay 5
			/next y
		} else {
			/message \at(\ag${Group.Member[${y}].Name}\at)\ay is here.
			/delay 5
			/next y
		}
		|---------------------------
		/delay 20s
	}
	|----------------------------

	/while (${Zone.ID} != ${TempleofMarr}) {
		/delay 5s
	}
	/call GroupWait
	/delay 2s

	/if (${Zone.ID} == ${TempleofMarr}) /message \ayI am currently in \am[\atTemple of Marr\am]\ay.\ax
	/delay 3s
	|------------------------
	|--- Reset the Cycle Loop
	/call IniChange "Theme" "CompletedPathTo" "FALSE"
	/call ForceSpawnStepReset
	|------------------------
	/message \arCAMPING TO DESKTOP !!!\ax
	/squelch /e3bcgza /camp desktop
	/delay 3s
	/end

/if (${Debugging}) /echo Sub CampInMarrs Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GoToMarrs
| --------------------------------------------------------------------------------------------
Sub GoToMarrs
	/if (${Debugging}) /echo Sub GoToMarrs Entry
	/declare y int local 1
	
	/message \arOoops..   your not in a valid starting zone for macro, Gating to Temple of Marr !
	/message \ayI am headed to \am[\atTemple of Marr\am]\ay.\ax
	
	|---------------------
	|--- Group - GoToMarrs
	|---------------------
	/delay 10
	/squelch /e3bcgza /nav stop
	/if (${GrpHasBRDClass}) /squelch /e3bct ${GrpBRDName} /playmelody stop
	/squelch /e3bcgza /keypress x
	/delay 6
	/squelch /e3bcgza /stand
	/delay 5
	/squelch /e3bcgza /alt act 511
	/delay 20s

	|----------------------------
	/while (${Group.Member[1].OtherZone} || ${Group.Member[2].OtherZone} || ${Group.Member[3].OtherZone} || ${Group.Member[4].OtherZone} || ${Group.Member[5].OtherZone}) {
		
		|--------------------------
		|--- Group - Start in Marrs
		|---------------------------
		/for y 1 to ${Group.Members} 
		/message \ayChecking status of: \at(\ag${Group.Member[${y}].Name}\at)\ay.
		/if (${Group.Member[${y}].OtherZone}) {
			/message \ar(${Group.Member[${y}].Name}) is NOT in ZONE !
			/squelch /e3bct ${Group.Member[${y}].Name} /nav stop
			/if (${Group.Member[${y}].Class.ShortName.Equal[BRD]}) /squelch /e3bct ${Group.Member[${y}].Name} /playmelody stop
			/squelch /e3bct ${Group.Member[${y}].Name} /keypress x
			/delay 5
			/squelch /e3bct ${Group.Member[${y}].Name} /stand
			/delay 5
			/squelch /e3bct ${Group.Member[${y}].Name} /alt act 511
			/delay 5
			/next y
		} else {
			/message \at(\ag${Group.Member[${y}].Name}\at)\ay is here.
			/delay 5
			/next y
		}
		|---------------------------
		/delay 20s
	}
	|----------------------------
	/message \agAll group members are here.
	|----------------------------
	/while (${Zone.ID} != ${TempleofMarr}) {
		/delay 5s
	}
	/call GroupWait
	/delay 2s
	|----------------------------
	
	/if (${Zone.ID} == ${TempleofMarr}) /message \ayI am currently in \am[\atTemple of Marr\am]\ay.\ax
	/call GoToDranikFromMarr

	/if (${Debugging}) /echo Sub GoToMarrs Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GoToDranikFromMarr
| --------------------------------------------------------------------------------------------
Sub GoToDranikFromMarr
	/if (${Debugging}) /echo Sub GoToDranik Entry
	/declare y int local 1
	
	|------------------------------
	/if (${Zone.ID} == ${TempleofMarr}) {
		/message \ayI am headed to \am[\atThe Ruined City of Dranik\am]\ay.\ax
		/delay 3s
	
		|----------------------------
		/while (${Group.Member[1].OtherZone} || ${Group.Member[2].OtherZone} || ${Group.Member[3].OtherZone} || ${Group.Member[4].OtherZone} || ${Group.Member[5].OtherZone}) {
			
			|--------------------------
			|--- Group - Start in Marrs
			|---------------------------
			/for y 1 to ${Group.Members} 
			/message \ayChecking status of: \at(\ag${Group.Member[${y}].Name}\at)\ay.
			/if (${Group.Member[${y}].OtherZone}) {
				/message \ar(${Group.Member[${y}].Name}) is NOT in ZONE !
				/squelch /e3bct ${Group.Member[${y}].Name} /nav stop
				/if (${Group.Member[${y}].Class.ShortName.Equal[BRD]}) /squelch /e3bct ${Group.Member[${y}].Name} /playmelody stop
				/squelch /e3bct ${Group.Member[${y}].Name} /keypress x
				/delay 5
				/squelch /e3bct ${Group.Member[${y}].Name} /stand
				/delay 5
				/squelch /e3bct ${Group.Member[${y}].Name} /alt act 511		
			} else {
				/message \at(\ag${Group.Member[${y}].Name}\at)\ay is here.
			}
			/next y
			|---------------------------
			/delay 20s
		}
		|----------------------------
		/message \agAll group members are here.
		|----------------------------
		/squelch /e3bcgza /tar Klonopin
		/delay 5
		/squelch /e3bcgza /nav target
		/delay 5
		/while (${Navigation.Active}) {
			/call SetLoc
			/call CheckStuck
			/delay 5
		}
		/call GroupWait
		/delay 2s
		|----------------------------
		
		:BarkDranik1
		/if (${Target.CleanName.Equal[Klonopin]}) {
			/e3bark dranik	
		} else {
			/squelch /e3bcgza /tar Klonopin
			/delay 5
			/goto :BarkDranik1
		}
		/delay 2s
	}
	|------------------------------
	|---------------
	/while (${Zone.ID} != ${RuinedCityofDranik}) {
		/delay 5s
	}
	|---------------
	/call GroupWait
	/delay 2s
	
	/if (${Zone.ID} == ${RuinedCityofDranik}) /message \ayI am currently in \am[\atThe Ruined City of Dranik\am]\ay.\ax
	/call GotoRecruiter
	
	/if (${Debugging}) /echo Sub GoToDranik Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GoToDranikFromNexus
| --------------------------------------------------------------------------------------------
Sub GoToDranikFromNexus
/if (${Debugging}) /echo Sub GoToDranik Entry

|------------------------------
/if (${Zone.ID} == ${Nexus}) {
	/message \ayI am headed to \am[\atThe Ruined City of Dranik\am]\ay.\ax
	/delay 3s
	/squelch /e3bcgza /tar Valium
	/delay 5
	/squelch /e3bcgza /nav target
	/delay 5
	/while (${Navigation.Active}) {
		/call SetLoc
		/call CheckStuck
		/delay 5
	}
	/call GroupWait
	/delay 2s

	:BarkDranik2
	/if (${Target.CleanName.Equal[Valium]}) {
		/e3bark dranik	
	} else {
		/squelch /e3bcgza /tar Valium
		/delay 5
		/goto :BarkDranik2
	}
	/delay 2s
}
|------------------------------
|---------------
/while (${Zone.ID} != ${RuinedCityofDranik}) {
	/delay 5s
}
|---------------
/call GroupWait
/delay 2s

/if (${Zone.ID} == ${RuinedCityofDranik}) /message \ayI am currently in \am[\atThe Ruined City of Dranik\am]\ay.\ax
/call GotoRecruiter

/if (${Debugging}) /echo Sub GoToDranik Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GoToDranikFromPoK
| --------------------------------------------------------------------------------------------
Sub GoToDranikFromPoK
/if (${Debugging}) /echo Sub GoToDranikFromPoK Entry

|------------------------------
/if (${Zone.ID} == ${PlaneofKnowledge}) {
	/message \ayI am headed to \am[\atThe Ruined City of Dranik\am]\ay.\ax
	/delay 3s
	/squelch /e3bcgza /tar Valium
	/delay 5
	/squelch /e3bcgza /nav target
	/delay 5
	/while (${Navigation.Active}) {
		/call SetLoc
		/call CheckStuck
		/delay 5
	}
	/call GroupWait
	/delay 2s
	
	:BarkDranik3
	/if (${Target.CleanName.Equal[Valium]}) {
		/e3bark dranik	
	} else {
		/squelch /e3bcgza /tar Valium
		/delay 5
		/goto :BarkDranik3
	}
	/delay 2s
}
|------------------------------
|---------------
/while (${Zone.ID} != ${RuinedCityofDranik}) {
	/delay 5s
}
|---------------
/call GroupWait
/delay 2s

/if (${Zone.ID} == ${RuinedCityofDranik}) /message \ayI am currently in \am[\atThe Ruined City of Dranik\am]\ay.\ax
/call GotoRecruiter

/if (${Debugging}) /echo Sub GoToDranikFromPoK Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GotoRecruiter
| --------------------------------------------------------------------------------------------
Sub GotoRecruiter
	/if (${Debugging}) /echo Sub GotoRecruiter Entry
	|----------- Ruined City of Dranik ------------
	/if (${Zone.ID} == ${RuinedCityofDranik}) {
		|---------------
		/if (!${Defined[Recruiter]}) {
			/declare Recruiter string outer Grand Historian Rygua
			/declare RecruiterLoc string outer ${Spawn[${Recruiter}].Y} ${Spawn[${Recruiter}].X} ${Spawn[${Recruiter}].Z}
		}
		|---------------
		|/removelev
		|----------------------------------------------
		|/echo {Spawn[${Recruiter}].Distance3D}=(${Spawn[${Recruiter}].Distance3D})
		:RecruiterDistanceCheck
		/if (${Spawn[${Recruiter}].Distance3D} <= 15) {
			/message \agI am next to \am[\at${Recruiter}\am]\ay \ag getting an expedition...
			/call GetExpedition
		} else {
			|-------------
			/if (${Spawn[${Recruiter}].Distance3D} > 15) {
				/message \agGoing to \ay[\ap${Recruiter}\ay] \ag to pick up an expedition...
				/if (${DoInvis}) /call CheckInvis
				/delay 1s
				
				|------------------------------------------
				/if (${DoInvis}) {
					|---------------------- NO INVIS VNAV !
					/call NavToLoc3 ${RecruiterLoc}
					|---------------------- NO INVIS VNAV !
				} else {
					|---------------------- INVIS VNAV !
					/call NavToLoc2 ${RecruiterLoc}
					|---------------------- INVIS VNAV !				
				}
				|------------------------------------------

				/delay 5
				|-------------
				|-------------
				/while (${Navigation.Active}) {
					/call SetLoc
					/call CheckStuck
					/delay 20
				}
				|-------------
				/call Group2Me
				/call GroupWait
				/if (${Me.XTarget}) /call DoClearTargets
				/doevents
				/goto :RecruiterDistanceCheck
			}
		}
		|----------------------------------------------
	}
	|----------- Ruined City of Dranik ------------

	/if (${Debugging}) /echo Sub GotoRecruiter Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GetExpedition (Called from GetExpedition)
| --------------------------------------------------------------------------------------------
Sub GetExpedition
	/if (${Debugging}) /echo Sub GetExpedition Entry

	/message \agGettting an Expedition . . .

	:RequestExpedition
	/if (${Target.ID} != ${Spawn[${Recruiter}].ID}) /target id ${Spawn[${Recruiter}].ID}
	/delay 2s ${Target.ID} == ${Spawn[${Recruiter}].ID}
	/if (${Target.ID} != ${Spawn[${Recruiter}].ID}) /goto :RequestExpedition

	|----------------------------!
	/if (${Target.ID} == ${Spawn[${Recruiter}].ID}) {
		|--------------------------
		/delay 1s
		/say catacombs
		:WaitForCorrectExpedition
		|-------------------------------------------------------------------------------------------
		|----  DO NOT MESS WITH HE DELAYS BEFORE AND AFTER /DOEVETS OR IT WILL NOT PICKUP EVENT !!!!
		/delay 1s
		/doevents
		/delay 1s
		|----  DO NOT MESS WITH HE DELAYS BEFORE AND AFTER /DOEVETS OR IT WILL NOT PICKUP EVENT !!!!
		|-------------------------------------------------------------------------------------------
		/if (${DranikCExpedition}==0) /goto :WaitForCorrectExpedition

		|-------------------------------
		|--- Have an Expedition -- C !!!
		/if (!${CurrentExpedition.Length}==0 && ${CurrentExpedition.Find[Catacombs of Dranik]}) {
			/squelch /target clear
			/squelch /e3bcgza /keypress alt+z
			/message \ayGoing to the expedition now . . . .
			|------------------------
			|--- Reset the Cycle Loop
			|------------------------
			/if (${DoRogueSosCoh} && ${GrpHasROGClass}) {
				/call IniChange "Theme" "CompletedPathTo" "TRUE"
			} else {
				/call IniChange "Theme" "CompletedPathTo" "FALSE"
			}
			|------------------------
			/call ForceSpawnStepReset
			|------------------------
			/call GoToExpedition
		}
		|--- Have an Expedition -- C !!!
		|-------------------------------
	}
	|----------------------------

	/if (${Debugging}) /echo Sub GetExpedition Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GoToExpedition
| --------------------------------------------------------------------------------------------
Sub GoToExpedition
	/if (${Debugging}) /echo Sub GoToExpedition Entry

	/message \ayI am headed to: \am[\atCatacombs of Dranik (Caza)\am]\ag
	
	|--- CHECK INVIS !!!
	/if (${DoInvis}) /call CheckInvis
	|--- CHECK INVIS !!!
	/delay 1s
	|------------------------------------------
	/if (${DoInvis}) {
		|---------------------- NO INVIS VNAV !
		/call NavToLoc3 1019.45 -290.80 -75.26
		|---------------------- NO INVIS VNAV !
	} else {
		|---------------------- INVIS VNAV !
		/call NavToLoc2 1019.45 -290.80 -75.26
		|---------------------- INVIS VNAV !				
	}
	|------------------------------------------	
	/delay 5

	|-------------
	/while (${Navigation.Active}) {
		/call SetLoc
		/call CheckStuck
		/delay 20
	}
	|-------------
	/call Group2Me
	/call GroupWait
	/if (${Me.XTarget}) /call DoClearTargets
	/doevents
	|----------------------------------------
	|/squelch /e3bcgz /removelev
	/squelch /e3bcgz /doortarget CASTLESWITCH
	/delay 2s
	/squelch /e3bcgz /click left door
	|----------------------------------------
	|/squelch /removelev
	/squelch /doortarget CASTLESWITCH
	/delay 2s
	/squelch /click left door
	|----------------------------------------
	/call Zoning

	|----------------------------------------
	/if (${Zone.ID}==${CataCombC}) {		
		/if (${GrpHasBRDClass}) {
			/call ResetBard
			/delay 2s
		}
		/squelch /e3bcg /multiline ; /afollow off ; /nav stop ; /stand
		/delay 5
		/squelch /followoff
		/delay 5
		/squelch /dropinvis 
		/delay 5
		|/squelch /droplev
		|/delay 5
		/if (${DoRogueSosCoh} && ${GrpHasROGClass}) /call Rogue_SOS_COH
	}
	|----------------------------------------

	/if (${Debugging}) /echo Sub GoToExpedition Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------------
| SUB: CheckExpeditionStatus
| --------------------------------------------------------------------------------------------------
Sub CheckExpeditionStatus
	/if (${Debugging}) /echo Sub CheckExpeditionStatus Entry

	|--------------------------------------------
	|--- GRAB THE CURRENT EXPEDITIOn DATA
	|--------------------------------------------
	/call CheckInADungeon
	/call CheckHaveDranikCExpedition
	/varset CompletedPathTo ${Ini[${IniFileName},Theme,CompletedPathTo]}
	|/echo InADungeon=(${InADungeon}) | CurrentExpedition=(${CurrentExpedition}) | DranikCExpedition=(${DranikCExpedition}) | CompletedPathTo=(${CompletedPathTo})
	|--------------------------------------------

	|-----------------------------------------------------------------
	| We are still in an ative expedition and in the expedition zone !
	|-----------------------------------------------------------------
	/if (${DranikCExpedition}==1 && ${InADungeon}==1) /return
	|-----------------------------------------------------------------

	|-----------------------------------------------------------------------
	|--- Expedition Over, but I haven't been booted out to Dranik yet !!!!
	|-----------------------------------------------------------------------
	:WaitTillIGetBooted
	/if (${DranikCExpedition}==0 && ${InADungeon}==1) {
		/message ==================================================================
		/message \ay - Looks like our expedition is over, but we havent been booted yet.\ax
		/message \ay - Waiting \am20\ay seconds until booted !\ax
		/message ==================================================================
		/if (!${Me.Combat} && !${Me.XTarget})  /delay 20s
		/call CheckInADungeon
		/if (${DranikCExpedition}==0 && ${InADungeon}==1) /goto :WaitTillIGetBooted
	}
	|-----------------------------------------------------------------------

	|-----------------------------------------------------------------------
	|--- Expedition Over, Already Booted out ... Get a new Expedition !
	|-----------------------------------------------------------------------
	/if (${DranikCExpedition}==0 && ${InADungeon}==0) {
		/message \ar-\ay I currently \arDO NOT HAVE\ay an expedition assigned to me !
		|-------------------
		/if ((${Zone.ID}==${RuinedCityofDranik}) && ${RepeatMission}) {
			|------------------------
			|--- Reset the Cycle Loop
			|------------------------
			/call IniChange "Theme" "CompletedPathTo" "FALSE"
			/call ForceSpawnStepReset
			|------------------------
			/message ==================================================================
			/message \ayI am headed to \am[\atGrand Historian Rygua\am]\ay to re-get an expedition.\ax
			/message ==================================================================
			/call GotoRecruiter
		}
		|-------------------
		/if (!${RepeatMission}) /call CampInMarrs
	}
	|-----------------------------------------------------------------------

	/if (${Debugging}) /echo Sub CheckExpeditionStatus Exit
	/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: DoClearTargets
| --------------------------------------------------------------------------------------------
Sub DoClearTargets
	/if (${Debugging}) /echo Sub DoClearTargets Entry
	
	/declare i 				int 	local	0
	/declare CurrentTarget 	int 	local	0
	
	|----------------------------------------------------------------------------------
	|-- Clear Target of PC or "Out of Range" NPC to pick up local 35 radius check mobs.
	|----------------------------------------------------------------------------------
	/if (${Target.ID} && (${Target.Type.Equal[pc]} || ${Target.Distance}>35)) {
		/if (${Target.ID} && (${Target.Type.Equal[pc]})) /message \ar~Initial~ \am[\atTarget\am]\ao ~ \am[\at${Target.CleanName}\am]\ao is a \am[\atPC\am]\ao, resetting target !\ax		
		/if (${Target.ID} && (${Target.Distance}>35)) /message \ar~Initial~ \am[\atTarget\am]\ao ~ \am[\at${Target.CleanName}\am]\ao is out of \am[\atLocal Range \am[\ay35\am]\am]\ao, resetting target !\ax
		/squelch /target /clear
	}
	|----------------------------------------------------------------------------------
	
	|--------------------------------------------------
	|-- MAIN DOCLEARTARGETS LOGIC
	|--------------------------------------------------
	/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]} || (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive})) {
		
		:gotoloopkeepfighting
		|------------------------
		/if (${Me.Sitting} || ${Me.Feigning}) /stand
		|------------------------
		
		|---------------------------------
		| Cler Target if Target is Corpse.
		|---------------------------------
		/if (${Target.Type.Find[corpse]}) {
			/squelch /target clear
		}
		|---------------------------------
		
		|--------------------------------------------------------------------------------------------------
		|-- Call PBAE_Enabled state detection if we have classe(s) and ${DoPBAOE}
		|--------------------------------------------------------------------------------------------------
		/if ((${GrpHasENCClass} || ${GrpHasWIZClass}) && ${DoPBAOE}) {
			|-------------------------------------
			/if (!${PBAE_State} && ${Target.ID} && ${Debugging}) {
				|-- Degub Condition
				/message ==================================================================
				/message \ayPBAE_DEBUGGER\ax
				/message \aoPBAE_State\ay=\am(\ag${PBAE_State}\am)\ao | \aoTargetID\ay=\am(\ag${Target.ID}\am)\ao | \aoTargetDistance\ay=\am(\ag${Target.Distance}\am)\ax
				/message \aoSpawnCount\ay=\am(\ag${SpawnCount[npc radius 25]}\am)\ao | \aoPBAOE_MobCount\ay=\am(\ag${PBAOE_MobCount}\am)\ao | \aoAggressive\ay=\am(\ag${Bool[${Spawn[npc radius 25].Aggressive}]}\am)\ax
				/message ==================================================================
			}
			|-------------------------------------
			/call CheckPBAELogic
		}
		|--------------------------------------------------------------------------------------------------
		
		|------------------------------
		|-- Dont have target, but aggressive mob near.
		|------------------------------
		/if (!${Target.ID} && ${Bool[${Spawn[npc radius 35].Aggressive}]}) {			
			|-----
			/if (!${Target.ID} && ${Navigation.PathExists[id ${Me.ID}]}) {
				/squelch /e3bcgz /nav id ${Me.ID}
			} else /if (!${Target.ID} && !${Navigation.PathExists[id ${Me.ID}]}) {
				/squelch /e3bcgz /moveto id ${Me.ID} mdist 10
			}
			|-----
			/delay 5
			/target id ${NearestSpawn[npc radius 35 targetable].ID}
			/delay 5
			|------------
			/if (${CurrentTarget}!=${NearestSpawn[npc radius 35 targetable].ID}) {
				/if (${Target.ID}!=0) /message \ayTargetting aggressive mob \aoID: \am[\at${NearestSpawn[npc radius 35 targetable].ID}\am] \aoName: \am[\at${NearestSpawn[npc radius 35 targetable].CleanName}\am]\ay and attacking !\ax
				/squelch /ClearTarget usemytarget
				/delay 5
				/varset CurrentTarget ${NearestSpawn[npc radius 35 targetable].ID}
			}
			|------------
		}
		|------------------------------
		
		|------------------------------
		|-- Have a target, kill it.
		|------------------------------
		/if (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive}) {				
			|-----
			/if (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive} && (${Target.Distance}>20) && ${Navigation.PathExists[id ${Target.ID}]}) {
				/squelch /nav id ${Spawn[npc fleeing].ID}
				/delay 5
				/squelch /e3bcgz /nav id ${Spawn[npc fleeing].ID}
			} else /if (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive} && (${Target.Distance}>20) && !${Navigation.PathExists[id ${Target.ID}]}) {
				/squelch /moveto id ${Spawn[npc fleeing].ID} mdist 10
				/delay 5
				/squelch /e3bcgz /moveto id ${Spawn[npc fleeing].ID} mdist 10
			}
			|-----
			/delay 5
			|------------
			/if (${CurrentTarget}!=${Target.ID}) {
				/if (${Target.ID}!=0) /message \ayTargetting aggressive mob \aoID: \am[\at${NearestSpawn[npc radius 35 targetable].ID}\am] \aoName: \am[\at${NearestSpawn[npc radius 35 targetable].CleanName}\am]\ay and attacking !\ax
				/squelch /ClearTarget usemytarget
				/delay 5
				/varset CurrentTarget ${Target.ID}
			}
			|------------
		}
		|------------------------------
		
		|------------------------------
		|-- RUNNER: Dont have target, Xtarget MOB may be fleeing.
		|------------------------------
		/if ((${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) || (${Me.XTarget} && ${Spawn[npc fleeing].ID}) || ${Spawn[npc fleeing].ID}) {

			|------------------------------
			/if (${Spawn[npc fleeing].ID}) {	
				|-----
				/if (${Spawn[npc fleeing].ID} && (${Spawn[npc fleeing].Distance}>20) && ${Navigation.PathExists[id ${Spawn[npc fleeing].ID}]}) {
					/squelch /nav id ${Spawn[npc fleeing].ID}
					/delay 5
					/squelch /e3bcgz /nav id ${Spawn[npc fleeing].ID}
				} else /if (${Spawn[npc fleeing].ID} && (${Spawn[npc fleeing].Distance}>20) && !${Navigation.PathExists[id ${Spawn[npc fleeing].ID}]}) {
					/squelch /moveto id ${Spawn[npc fleeing].ID} mdist 10
					/delay 5
					/squelch /e3bcgz /moveto id ${Spawn[npc fleeing].ID} mdist 10
				}
				|-----
				/delay 5			
				/target id ${Spawn[npc fleeing].ID}				
				/delay 5
				|------------
				/if (${CurrentTarget}!=${Spawn[npc fleeing].ID}) {
					/if (${Target.ID}!=0) /message \arFound a \am[\atRandom\am]\ar fleeing mob! \ayTargetting \aoID: \am[\at${Me.XTarget[${i}].ID}\am] \ayName\ao: \am[\at${Me.XTarget[${i}].CleanName}\am]\ay and attacking !\ax
					/squelch /ClearTarget usemytarget
					/delay 5
					/varset CurrentTarget ${Spawn[npc fleeing].ID}
				}
				|------------				
			}
			|------------------------------
			
			|------------------------------
			|-- Xtarget
			/if ((${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) || (${Me.XTarget} && ${Spawn[npc fleeing].ID})) {
				|-----
				/if (${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) {
					/message \aoAn XTarget mob is out of range, hunting it down !\ax
				}
				|-----

				|-----
				/if	(${Me.XTarget} && ${Spawn[npc fleeing].ID}) {
					/message \aoXTarget mob is fleeing, chasing it down !\ax
				}
				|-----				
			
				|------------------
				/if	(${Me.XTarget}) {
					/for i 1 to ${Me.XTargetSlots}
						/if (${Me.XTarget[${i}].ID}) {	
							|-----
							/if (${Me.XTarget} && (${Me.XTarget[${i}].Distance}>20) && ${Navigation.PathExists[id ${Me.XTarget[${i}].ID}]}) {
								/squelch /nav id ${Me.XTarget[${i}].ID}
								/delay 5
								/squelch /e3bcgz /nav id ${Me.XTarget[${i}].ID}
							} else /if (${Me.XTarget} && (${Me.XTarget[${i}].Distance}>20) && !${Navigation.PathExists[id ${Me.XTarget[${i}].ID}]}) {
								/squelch /moveto id ${Me.XTarget[${i}].ID}
								/delay 5
								/squelch /e3bcgz /moveto id ${Me.XTarget[${i}].ID}
							}
							|-----
							/delay 5			
							/target id ${Me.XTarget[${i}].ID}
							/delay 5		
							|------------
							/if (${CurrentTarget}!=${Me.XTarget[${i}].ID}) {
								/if (${Target.ID}!=0) /message \arFound a \am[\atXTarget\am]\ar fleeing mob! \ayTargetting \aoID: \am[\at${Me.XTarget[${i}].ID}\am] \ayName\ao: \am[\at${Me.XTarget[${i}].CleanName}\am]\ay and attacking !\ax
								/squelch /ClearTarget usemytarget
								/delay 5
								/varset CurrentTarget ${Me.XTarget[${i}].ID}
							}
							|------------
							/break
						}
					/next i
				}				
				|------------------
			}
			|------------------------------
		}
		|------------------------------
		|-- RUNNER
		|------------------------------	
		
		|------------------------------
		| Target Distance Stick Check
		|------------------------------
		/if (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive} && (${Target.Distance} > 20)) {	
			/if (${Target.ID}!=0) /message \ayMob \aoID: \am[\at${Target.ID}\am] \ag|\ax \aoName: \am[\at${Target.CleanName}\am]\ay \ag|\ax \aoDistance: \am[\at${Target.Distance}\am]\ay is \ar[TOO FAR AWAY]\ay, adjusting group !\ax
			|--
			/if (${Navigation.PathExists[id ${Target.ID}]}) {
					/squelch /nav id ${Target.ID}
					/delay 2s ${Target.Distance}<=20
					/squelch /e3bcgz /nav id ${Me.ID}					
				} else {
					/squelch /moveto id ${Target.ID} mdist 10
					/delay 2s ${Target.Distance}<=20
					/squelch /e3bcgz /moveto id ${Me.ID} mdist 10
			}
			|--
			/stick 15
			/delay 5
		} else {
			/stick 15
			/delay 5
		}
		|------------------------------

		|------------------------------
		| Target LineOfSight Check
		|------------------------------
		/if (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive} && !${Target.LineOfSight}) {	
			/if (${Target.ID}!=0) /message \ayMob \aoID: \am[\at${Target.ID}\am] \ag|\ax \aoName: \am[\at${Target.CleanName}\am]\ay \ag|\ax \aoDistance: \am[\at${Target.Distance}\am]\ay is \ar[NOT IN LINE OF SIGHT]\ay, adjusting group !\ax
			|---------------------
			/if (${Navigation.PathExists[id ${Target.ID}]}) {
					/squelch /nav id ${Target.ID}
					/delay 2s ${Target.LineOfSight}
					/squelch /face fast
					/squelch /e3bcgz /nav id ${Me.ID}					
				} else {
					/squelch /moveto id ${Target.ID} mdist 10
					/delay 2s ${Target.LineOfSight}
					/squelch /face fast
					/squelch /e3bcgz /moveto id ${Me.ID} mdist 10
			}
			|---------------------
		}		
		|------------------------------	
			
		|-------------------------- DO BURNS -----------------------------------------
        /if (${Target.ID} && ${Me.Combat} && ${Target.Type.Equal[npc]} && ${DoBurns}) {
			| --- Explosion of Spite
			/if (${SpawnCount[npc radius 50]} >2 && ${Spawn[npc radius 50].Aggressive} && ${Cast.Ready[749]}) {
				/alt act 749
				/if (${DoBurns}) /quickburn
				/if (${DoBurns}) /longburn
				/delay 20
				/goto :gotoloopkeepfighting
			}
			| --- Explosion of Hatred
			/if (${SpawnCount[npc radius 50]} >4 && ${Spawn[npc radius 50].Aggressive} && ${Cast.Ready[822]}) {
				/alt act 822
				/if (${DoBurns}) /fullburn
				/delay 20
				/goto :gotoloopkeepfighting
			}
			| --- Projection of Doom
			/if (${SpawnCount[npc radius 50]} >6 && ${Spawn[npc radius 50].Aggressive} && ${Cast.Ready[3215]} && ${DoBurns}) /alt act 3215
			| --- EpicBurn
			/if (${SpawnCount[npc radius 50]} >4 && ${Spawn[npc radius 50].Aggressive} && ${DoBurns}) /epicburn
			| --- Vicious Bite of Chaos
			/if ((${Me.PctHPs} < 95) && ${Cast.Ready[825]} && ${DoBurns})  /alt act 825
			| --- Chattering Bones
			/if (${Cast.Ready[3822]} && ${DoBurns}) /alt act 3822
			| --- Encroaching Darkness
			/if ((${SpawnCount[npc radius 50]} <3) && ${Spawn[npc radius 50].Aggressive} && ${Cast.Ready[826]}) {
				/squelch /e3bcgz /nav target
				/assistme
				/alt act 826
			}
            /delay 2s
            /if (${Debugging}) /echo DEBUG: KillMob: Combat Loop

            /goto :gotoloopkeepfighting
        }
		|-------------------------- DO BURNS -----------------------------------------
		
		|--------------------------------------------------
		/if	(${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]} || (${Target.ID} && ${Target.Type.Equal[npc]} && ${Target.Aggressive})) /goto :gotoloopkeepfighting
		|--------------------------------------------------
	}
	|--------------------------------------------------
	|-- MAIN DOCLEARTARGETS LOGIC
	|--------------------------------------------------

	|----------------------
	|--- Reset CurrentTarget
	|----------------------
	/varset CurrentTarget 0
	|----------------------
	
	|------------------------
	|-- FORCE TURN OFF PBAE
	|------------------------
	/if (${PBAE_State}) {			
			/varset PBAE_State FALSE
			/message \aoPBAE is currently \am[\arENABLED\am]\ao, disabling \am[\atPBAE\am]\ao now.\ax
			/pbaeoff
	}
	|------------------------
	
	|-----------------------------------
	/if (!${Me.XTarget} || (!${Target.ID} && !${Bool[${Spawn[npc radius 50].Aggressive}]})) /squelch /target clear
	|-----------------------------------
	/if (${Debugging}) /echo Sub DoClearTargets Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckPBAELogic
| --------------------------------------------------------------------------------------------
Sub CheckPBAELogic
	/if (${Debugging}) /echo CheckPBAELogic Sub Entry
	
	|-- TURN ON PBAE
	/if (!${PBAE_State} && ${Target.ID} && (${Target.Distance}<=25) && (${SpawnCount[npc radius 25]}>=${PBAOE_MobCount}) && ${Bool[${Spawn[npc radius 25].Aggressive}]}) {
		/varset PBAE_State TRUE
		/message \aoPBAE is currently \am[\agDISABLED\am]\ao: ~ \am[\arENABLING\am]\ao ~ \am[\atPBAE\am]\ao now.\ax
		/popcustom 13 2 -> PBAE ON <
		/pbaeon
	}
	|-- TURN OFF PBAE
	/if (${PBAE_State} && ${Target.ID} && (${Target.Distance}<=25) && (${SpawnCount[npc radius 25]}<${PBAOE_MobCount}) && ${Bool[${Spawn[npc radius 25].Aggressive}]}) {			
		/varset PBAE_State FALSE
		/message \aoPBAE is currently \am[\arENABLED\am]\ao: ~ \am[\agDISABLING\am]\ao ~ \am[\atPBAE\am]\ao now.\ax
		/popcustom 2 2 -> PBAE OFF <-
		/pbaeoff
	}
	|-------------------------------------------------------------

	/if (${Debugging}) /echo CheckPBAELogic Sub Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: DoSinglePull
| --------------------------------------------------------------------------------------------
Sub DoSinglePull(string Enemy)
	/if (${Debugging}) /echo DoSinglePull Sub Entry
	|-------------------------
	/call CheckCasting
	|-------------------------
	/varset CampX ${Me.X}
	/varset CampY ${Me.Y}
	/varset CampZ ${Me.Z}
	|--------------------
	/if (${Bool[${Enemy}]}) {
		/varset FarmMob ${Enemy}
		/if (${Debugging} && !${reportTarget}) {
			/message Looking for: ${FarmMob}
			/varset reportTarget ${reportTarget.OriginalValue}
		}
	} else /if (!${reportTarget}) {
		/message \arAttacking \ay[\apAnything I can get my grubby paws on\ay]\ar.
		/varset reportTarget ${reportTarget.OriginalValue}
		|--------------------
		/if (${myTargetID} && !${Target.Type.Equal[Corpse]} && !${Target.Type.Equal[Pet]} && !${Target.Type.Equal[PC]}) {
			/if (${Spawn[id ${Target.ID}].Distance} > 30) /squelch /nav id ${Target.ID}
			|--------------------
			/if (${Spawn[id ${Target.ID}].Distance} < 30) {
				/if (${Target.ID}) /face
				/squelch /attack on
				|/if (${Select[${Me.Class.ShortName},SHD,MAG,NEC,BST,SHM,ENC,DRU]} && ${Me.Pet.ID}) /pet attack
				/doevents
				/if (${UseClickDamage}) /call Clickies_Damage
			}
			|--------------------
			/varcalc BackUpTimer (${BackUpTimer})+1
			|--------------------
			/if (${BackUpTimer}>7) {
				/message \ayHaving trouble getting to a target.. Attempting to get back on mesh.
				/if (${Debugging}) /echo Setting BackUpTimer Plus 1
				/call BackUp
				/varset BackUpTimer 0
			}
			|--------------------
			/if (${AssistMe}) {
				/if (${Debugging}) /e3bcgz (Line: ${Macro.CurLine}) killthis
				/squelch /e3bcgz /nav id ${Me.ID}
				/squelch /e3bcgz /target id ${Me.XTarget}
				/timed 10 /squelch /e3bcgz /assistme
				|/timed 15 /squelch /e3bcgz /pet attack
				|/timed 20 /squelch /e3bcgz /pet swarm
				
			}	
			|--------------------
		}
		|--------------------
	}
	|--------------------
	
	:findMob
	/if (${Debugging}) /echo FindMob DoSinglePull
	/if (${Target.Type.Equal[corpse]}) {
		/if (${Target.ID} == ${myTargetID}) /varset myTargetID 0
		/squelch /target clear
	}
	/if (${Window[RespawnWnd].Open}) /call GroupDeathChk
	/if (!${Me.XTarget} && ${CheckBots}) {
		/call GroupDeathChk
		/call GroupManaChk
		/call GroupEndChk
	}
	/if (${Debugging}) /echo \aymyTargetID has an ID: ${Spawn[id ${myTargetID}].ID} - is a corpse: ${Spawn[id ${myTargetID}].Type.Equal[Corpse]} - I have an XTarget: !${Me.XTarget}
	/if (!${Spawn[id ${myTargetID}].ID} || ${Spawn[id ${myTargetID}].Type.Equal[Corpse]} && !${Me.XTarget} && !${Me.Casting.ID}) {
		/message \ayLooking for a target!
		/varset myTargetID 0
		|-------------------
		/call TargetShortest
		|-- /message \atMy Target: \ay[\ap${Spawn[id ${myTargetID}].Name}\ay] [\ap${myTargetIDLoc}\ay]		
		|/delay 1s
		|/echo \atMy Target: \ay[\ap${Spawn[id ${myTargetID}].Name}\ay]
		|-------------------
	} else {
		/if (${Debugging}) /echo \ayI have an XTarget so I'm going to set that as my target.
		|---------------------------------------
		/if (${Me.XTarget}) {
			/varset myTargetID ${Target.ID}
			/if (${Debugging}) /echo CALL DoClearTargets
			/if (${Me.XTarget} || ${Spawn[id ${Target.ID}].Distance} < 30) /call DoClearTargets
			/if (${Debugging}) /echo END CALL DoClearTargets			
		}
		|---------------------------------------
	}
	:navto
	/if (${Debugging}) /echo DoSinglePull NAVTO
	/if (${Target.ID}) /squelch /target clear
	/if ((${Spawn[${myTargetID}].Distance} > 30 && !${Target.Type.Equal[corpse]} && !${Me.XTarget}) || !${Spawn[${myTargetID}].LineOfSight}) {
		/if (!${Spawn[${myTargetID}].ID}) {
			/squelch /target clear
			/if (${Debugging}) /echo \ar My target ID was null, so I'm returning out of the sub.
			/return
		}
		/varset BackUpTimer 0
		/message \agNavigating to: \ay[\ap${Spawn[${myTargetID}].CleanName}\ay] \agID: \ay[\ap${myTargetID}\ay] \agDistance: \ay[\ap${Spawn[${myTargetID}].Distance}\ay]
		/if (${Debugging}) /echo \ayNavigating to ${Spawn[${myTargetID}].Name} ID: ${myTargetID} Distance: ${Spawn[${myTargetID}].Distance} > 30 - Line of Sight: ${Spawn[${myTargetID}].LineOfSight}
		/call WaitNav ${myTargetID}
		/delay 10
		/if (${Debugging}) /echo Navigating to the enemy.
		/call SetLoc
		/call CheckStuck
		/delay 5
		/goto :navto
	} else /if (!${Target.ID} || ((${Target.ID}!=${myTargetID}) && (${Target.ID}!=${Me.ID}) && (${myTargetID}!=0) && !${Me.XTarget})) {
		/target id ${myTargetID}
		/if (${Navigation.Active}) /nav stop
	}
	/delay 5
	|----------------------------------------------------------------------------------------------------
	/docommand ${If[${PullAbilityRange}>30,/stop,/stick moveback uw 10]}
	/if (${Spawn[${myTargetID}].Distance}<=30 && !${Spawn[${myTargetID}].Aggressive}) /squelch /attack on
	|----------------------------------------------------------------------------------------------------
	|-----------------------------------------------
	/if (${Debugging}) /echo DoSinglePull Sub Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: TargetShortest
| --------------------------------------------------------------------------------------------
Sub TargetShortest
	/if (${Debugging}) /echo Sub TargetShortest Entry

	/if (${UseClickBuffs}) /call Clickies_Buffs
	/declare MobsInRadius 	int 	local 	${SpawnCount[npc noalert 1 targetable radius ${CampRadius} zradius ${ZRadius} alert 10]}


	|- Makes scanning in big zones super efficient.
	/if (${MobsInRadius} > 5) {
		/varset MobsInRadius 5
	}
	/declare MobCounter 	int 	local 	0
	/declare MobID 			int 	local 	0
	/declare PathLength		float	local	0
	/declare MobIDDistance	float	local	0
	/declare PathCount		int		local	1
	/declare PathShortest	int 	local 	0
	/declare MobIDValid		int		local	0
	/if (${Resting}) /return

	/varset myTargetID 0
	/if (${MobsInRadius}) {
		/for MobCounter 1 to ${MobsInRadius}
		/varset MobID ${NearestSpawn[${MobCounter},npc targetable radius ${CampRadius} zradius ${ZRadius} alert 10 noalert 1].ID}

		|-- ORIGINAL LIST TO FILTER
		|/if (${Select[${Spawn[ID ${MobID}].Type},PET,AURA,BANNER,CAMPFIRE,CORPSE,CHEST,ITEM,TRIGGER,TRAP,TIMER,MOUNT,MERCENARY,OBJECT]} && !${Ini[${MobIgnore},${Zone.ShortName},Ignored].Find[ID ${MobID}]}) /continue

		|-- REVISED LIST TO FILTER
		/if (${Select[${Spawn[ID ${MobID}].Type},PC,Untargetable,Mount,Pet,Corpse,Chest,Trigger,Trap,Timer,Item,Mercenary,Aura,Object,Banner,Campfire,Flyer]} && !${Ini[${MobIgnore},${Zone.ShortName},Ignored].Find[ID ${MobID}]}) /continue

		|-- Filter out anything without an actual CleanName ( DOORS )
		/if (!${Spawn[ID ${MobID}].CleanName.Length}) /continue

		|-- Filter out anything with an actual Surname   ( Named )
		/if (${Spawn[ID ${MobID}].Surname.Length}) /continue

		|------- HARD CODED EXCEPTIONS
		|/if (${Spawn[ID ${MobID}].CleanName.Equal[a hatchling]} || ${Spawn[ID ${MobID}].CleanName.Equal[a creaking crate]} || ${Spawn[ID ${MobID}].CleanName.Equal[a hollow tree]} || ${Spawn[ID ${MobID}].CleanName.Equal[a petrified colossal tree]}) {
		|/continue
		|}
		|------- HARD CODED EXCEPTIONS

		/varset MobIDValid 0
		/varset PathLength ${Navigation.PathLength[id ${MobID}]}
		/if (${PathLength} > 0) {
			/if (${PathCount}==1) {
				/varset myTargetID ${MobID}
				/varset PathShortest ${PathLength}
			} else /if (${PathLength} <= ${PathShortest}) {
				/varset myTargetID ${MobID}
				/varset PathShortest ${PathLength}
			}
			/varcalc PathCount ${PathCount}+1
		}

		/next MobCounter
		/if (${myTargetID}) /message \agPulling \ay[\ap${Spawn[${myTargetID}].CleanName}\ay] \agNPCID:\ay[\ap${myTargetID}\ay] \awat \ay[\at${PathShortest}\ay] \awfeet.
		/varset Announce FALSE
		/varset notkillable 0
	} else {
		/varset myTargetID 0
		/delay 5s ${Me.XTarget} == 0
		/if (!${Me.XTarget}) {
			/if (!${Announce}) {
				/message No more mobs to pull, lets Wait for Respawn!
				/varset Announce TRUE
			}
			/varset notkillable 0
			/if (${Me.Standing} && !${Navigation.Active}) /sit
		}
		/if (${Me.XTarget}) /return
	}
	/delay 1
	/if (${Debugging}) /echo Sub TargetShortest exit
	/varcalc BackUpTimer (${BackUpTimer})+1
	/if (${Debugging}) /echo Setting BackUpTimer +1 to ${BackUpTimer}
	/if (${Debugging} && ${BackUpTimer}>1) /echo \arCould Be Stuck ${BackUpTimer}
	|------------------------
	/if (${BackUpTimer}>10) {
		/if (!${Me.XTarget}) /call ReturnToCamp
		/delay 1s
		/message \ayHaving trouble getting to a target.. Attempting to get back on mesh.
		/if (${Debugging}) /echo Setting BackUpTimer Plus 1
		/call BackUp
		/delay 1s
		/varset BackUpTimer 0
	}
	|------------------------

	/if (${Debugging}) /echo Sub TargetShortest Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------------
| SUB: SwarmPullStepMove_1   Receive: SpawnPull_Step from Go2LastSwarmLoc
| --------------------------------------------------------------------------------------------------
Sub SwarmPullStepMove_1(string SpawnPull_Step)
	/declare x 						int 	local 	${SpawnPull_Step}
	/declare TempSpawnPull_Loc		string 	local	NULL

	/if (${Debugging}) /echo Sub SwarmPullStepMove_1 Entry
	/if (${Debugging}) /echo SpawnPull_Loc=(${SpawnPull_Loc}) | SpawnPull_Step=(${SpawnPull_Step})

	/message ==================================================================
	/message \ag+++\ax \ayStarting \arSpawnPull \atPathTo \agCycle:\ax \ao...\ax \arLets go !\ax
	/message ==================================================================

	|----------------------------------------------------------------------------------------------
    /for x ${SpawnPull_Step} to ${LocalStepArray_${Zone.ShortName}_1.Size}
		/varset TempSpawnPull_Loc ${LocalStepArray_${Zone.ShortName}_1[1,${x}]}
		|-----------------------------
		/if (${TempSpawnPull_Loc.Equal[NULL]}) {
			/message \ar The Catacomb steps did not load correctly, reloading !
			/call DoSwarmPull_PathTo
			/delay 10
		}
		|-----------------------------

		|------------------------------------------
		/if (!${Me.XTarget} && ${CheckBots}) {
			/call GroupDeathChk
			/call GroupManaChk
			/call GroupEndChk
		}
		|------------------------------------------

		|------------------------------------------
		| Move group to me before next step
		|------------------------------------------
		/message \at - Calling the group to me before moving to the next step . . . .
		/call GroupWait
		/delay 1s
		|------------------------------------------

		|-------------------------
		/call CheckCasting
		|-------------------------

		|-----------------------------------------------
		|/echo \arSwarmPullStepMove: \ayTempSpawnPull_Loc=(${TempSpawnPull_Loc})
		|-----------------------------------------------
		/if (!${Me.Combat} && !${Me.XTarget}) /call CheckExpeditionStatus
		/if (${TempSpawnPull_Loc.Length}>0 && ${DranikCExpedition}==1 && ${InADungeon}==1) {
			/message \agNext location to Nav to is: \aySTEP: \ay[\am${x}\ay] of \ay[\am${LocalStepArray_${Zone.ShortName}_1.Size}\ay] Coordinates: [\am${TempSpawnPull_Loc}\ay]
			|--------------------------------------------------------------
			|/echo \agARRAY RETURNED DATA for step \ay[${x}]\ag: TempSpawnPull_Loc=(\am${TempSpawnPull_Loc})
			|--------------------------------------------------------------
			/if (!${Me.Combat} && !${Me.XTarget} && (${InADungeon}==1) && (${DranikCExpedition}==1)) {
				|----------------------------------------------
				|-- Just nav to loc, using NavToLoc function will cause you to engage mobs along the path !
				|----------------------------------------------
				/squelch /nav loc ${TempSpawnPull_Loc}
				/delay 7
				/squelch /e3bcgza /nav loc ${TempSpawnPull_Loc}					
				|----------------------------------------------
			}
			|--------------------------------------------------------------
			/while (${Navigation.Active}) {
				/call SetLoc
				/call CheckStuck
				/delay 5
			}
			/squelch /e3bcgz /nav id ${Me.ID}
			/delay 5
			|----------------------------------------------------------

			|-------------------------------------------------------------------------------------------------------
			|- WRITE: LastSwarmed_Dungeon and LastSwarmed_Step to ini file, to pickup at this point if we break macro.
			|-------------------------------------------------------------------------------------------------------
			/call IniChange "Theme" "LastSwarmed_Dungeon" ${Zone.ShortName}
			/call IniChange "Theme" "LastSwarmed_Step" ${x}
			|-------------------------------------------------------------------------------------------------------

			|---------------------------------------------------------------
			| Use the DoClearTargets for SPawnPull system instead, of COMBAT
			|---------------------------------------------------------------
			/if (${Me.XTarget}) /call DoClearTargets
			/doevents
			/delay 10
		}
		|-----------------------------------------------
		| Before we go to next step ...   ECheck if we should loot Corpses.	
		/if (${LootCorpse} && !${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /call CheckForCorpses
		| Before we go to next step ...   EXIT the loop if we have mission success !
		|-----------------------------------------------
		/if (!${Me.Combat} && !${Me.XTarget}) /call CheckExpeditionStatus
    /next x
	|----------------------------------------------------------------------------------------------

	|------------------
	/if (${ReclaimDC}) /call ReclaimAltDC
	|------------------

	|------------------------------------------
	/if (!${Me.XTarget} && ${CheckBots}) {
		/call GroupDeathChk
		/call GroupManaChk
		/call GroupEndChk
	}
	|------------------------------------------

	/message ==================================================================
	/message \atCompleted all SwarmPull "PathTo" steps.\ax
	/message \atUpdating (\ay${IniFileName})\ax INI file with PathTo completion.\ax
	/call IniChange "Theme" "CompletedPathTo" "TRUE"
	/call ForceSpawnStepReset
	/varset SpawnPull_Step 1
	/message \ayStarting Main Cycle Run !!!\ax
	/message ==================================================================
	/delay 3s
	|------------------------------------------------------
	/if (!${BiggerSwarms}) {
		/call DoSwarmPull_MainLoop
	} else {
		/call DoSwarmPull_MainLoop_Bigger
	}
	|------------------------------------------------------
	/delay 10

	/if (${Debugging}) /echo Sub SwarmPullStepMove_1 Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------------
| SUB: SwarmPullStepMove_2   Receive: SpawnPull_Step from Go2LastSwarmLoc
| --------------------------------------------------------------------------------------------------
Sub SwarmPullStepMove_2(string SpawnPull_Step)
	/declare x 						int 	local 	${SpawnPull_Step}
	/declare TempSpawnPull_Loc		string 	local	NULL
	/declare mStrLoc				string	local	NULL
	/declare mNavLocY				int		local	NULL
	/declare mNavLocX				int		local	NULL
	/declare SpawnsAtStep			int		local	NULL
	/declare CampReturnLoc			string	local	1905.66 336.42 -134.67

	/if (${Debugging}) /echo Sub SwarmPullStepMove_2 Entry
	/if (${Debugging}) /echo SpawnPull_Loc=(${SpawnPull_Loc}) | SpawnPull_Step=(${SpawnPull_Step})

	:MainLoopCycle
	/delay 1s
	/message ==================================================================
	/message \ag+++\ax \ayStarting \arSpawnPull \atMainLoop \agCycle:\ax \ao...\ax \arLets go !\ax
	/message ==================================================================
	/delay 3s
	|-------------------------------------------------------------------------------------------------------
    /for x ${SpawnPull_Step} to ${LocalStepArray_${Zone.ShortName}_2.Size}
		/varset TempSpawnPull_Loc ${LocalStepArray_${Zone.ShortName}_2[1,${x}]}
		|-----------------------------
		/if (${TempSpawnPull_Loc.Equal[NULL]}) {
			/message \ar The Catacomb steps did not load correctly, reloading !
			/call DoSwarmPull_MainLoop
			/delay 1s
		}
		|-----------------------------

		|------------------------------------------
		/varset mNavLocY ${TempSpawnPull_Loc.Arg[1, ]}
		/varset mNavLocX ${TempSpawnPull_Loc.Arg[2, ]}
		|-------------------------
		/if (${mNavLocY}>=0) {
            /varset mStrLoc ${mNavLocX} ${mNavLocY}
        } else {
            /varset mStrLoc (${mNavLocX} ${mNavLocY})
        }
		 |-------------------------
		/varset SpawnsAtStep ${SpawnCount[npc loc ${mNavLocX} ${mNavLocY} radius 100]}
		|/echo SpawnsAtStep=(${SpawnsAtStep})
		|/echo  mStrLoc=(${mStrLoc}) | mNavLocY=(${mNavLocY}) | mNavLocYX(${mNavLocX})
		|------------------------------------------

		|------------------------------------------
		/if (!${Me.XTarget} && ${CheckBots}) {
			/call GroupDeathChk
			/call GroupManaChk
			/call GroupEndChk
		}
		|------------------------------------------

		|------------------------------------------
		| Move group to me before next step
		|------------------------------------------
		/message \at - Calling the group to me before moving to the next step . . . .
		/call GroupWait
		/delay 1s
		|------------------------------------------

		|-------------------------
		/call CheckCasting
		|-------------------------

		|-----------------------------------------------
		|/echo \arSwarmPullStepMove: \ayTempSpawnPull_Loc=(${TempSpawnPull_Loc})
		|-----------------------------------------------
		/if (!${Me.Combat} && !${Me.XTarget}) /call CheckExpeditionStatus
		/if (${TempSpawnPull_Loc.Length}>0 && ${DranikCExpedition}==1 && ${InADungeon}==1) {
			/message \agNext location to Nav to is: \aySTEP: \ay[\am${x}\ay] of \ay[\am${LocalStepArray_${Zone.ShortName}_2.Size}\ay] Coordinates: [\am${TempSpawnPull_Loc}\ay]
			|-----------------------------------------------------------------------------------------------------------------------------
			/if (${SpawnsAtStep}>=1) {
				/message \ao - STEP: \ay[\am${x}\ay] of \ay[\am${LocalStepArray_${Zone.ShortName}_2.Size}\ay] has \at*\ay[\ar${SpawnsAtStep}\ay]\at* \ayspawns, \agKILL THEM ALL\ax \ao!!!\ax
				|--------------------------------------------------------------
				|/echo \agARRAY RETURNED DATA for step \ay[${x}]\ag: TempSpawnPull_Loc=(\am${TempSpawnPull_Loc})
				|--------------------------------------------------------------
				/if (!${Me.Combat} && !${Me.XTarget} && (${InADungeon}==1) && (${DranikCExpedition}==1)) {
					|----------------------------------------------
					|-- Just nav to loc, using NavToLoc function will cause you to engage mobs along the path !
					|----------------------------------------------
					/squelch /nav loc ${TempSpawnPull_Loc}
					/delay 7
					/squelch /e3bcgza /nav loc ${TempSpawnPull_Loc}
					|----------------------------------------------
				}
				|------------------------------
				/while (${Navigation.Active}) {
					/call SetLoc
					/call CheckStuck
					/delay 5
				}
				|------------------------------
				/squelch /e3bcgz /nav id ${Me.ID}
				/delay 5
				|----------------------------------------------------------

				|-------------------------------------------------------------------------------------------------------
				|- WRITE: LastSwarmed_Dungeon and LastSwarmed_Step to ini file, to pickup at this point if we break macro.
				|-------------------------------------------------------------------------------------------------------
				/call IniChange "Theme" "LastSwarmed_Dungeon" ${Zone.ShortName}
				/call IniChange "Theme" "LastSwarmed_Step" ${x}
				|-------------------------------------------------------------------------------------------------------
			} else {
				/message \ao - STEP: \ay[\am${x}\ay] of \ay[\am${LocalStepArray_${Zone.ShortName}_2.Size}\ay] has [\at${SpawnsAtStep}\ay] spawns, \arSKIPPING\ax \ao!!!\ax
				|-------------------------------------------------------------------------------------------------------
				|- WRITE: LastSwarmed_Dungeon and LastSwarmed_Step to ini file, to pickup at this point if we break macro.
				|-------------------------------------------------------------------------------------------------------
				/call IniChange "Theme" "LastSwarmed_Dungeon" ${Zone.ShortName}
				/call IniChange "Theme" "LastSwarmed_Step" ${x}
				|-------------------------------------------------------------------------------------------------------
			}
			|-----------------------------------------------------------------------------------------------------------------------------
			|---------------------------------------------------------------
			| Use the DoClearTargets for SPawnPull system instead, of COMBAT
			|---------------------------------------------------------------
			/if (${Me.XTarget}) /call DoClearTargets
			/doevents
			/delay 10
		}
		|-----------------------------------------------
		| Before we go to next step ...   ECheck if we should loot Corpses.	
		/if (${LootCorpse} && !${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /call CheckForCorpses
		| Before we go to next step ...   EXIT the loop if we have mission success !
		|-----------------------------------------------
		/if (!${Me.Combat} && !${Me.XTarget}) /call CheckExpeditionStatus
    /next x
	|-------------------------------------------------------------------------------------------------------

	| --- NAV TO CampReturnLoc
	/message ==================================================================
	/message \ag+++\ax \aoCompleted \arSpawnPull \atMainLoop \agCycle:\ax \ao...\ax \atRETURNING TO CAMP !!!\ax
	/message ==================================================================

	|---------------		
	|-- MOVE TO CAMP
	|---------------		
	|-------------------------------
	/call NavToLoc2 ${CampReturnLoc}
	|-------------------------------
	
	:WaitTillAtCamp
	/if (${Me.Moving}) /delay 5
	/if (${Me.Moving}) /goto :WaitTillAtCamp
	
	|----------------------------------------------------------------
	|-- Clear the camp location of any corpses before the next cycle.
	|----------------------------------------------------------------
	/if (${LootCorpse} && !${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /call CheckForCorpses
	|----------------------------------------------------------------

	|------------------
	/if (${ReclaimDC}) /call ReclaimAltDC
	|------------------

	|------------------------------------------
	/if (!${Me.XTarget} && ${CheckBots}) {
		/call GroupDeathChk
		/call GroupManaChk
		/call GroupEndChk
	}
	|------------------------------------------

	/message ==================================================================
	/message \ag+++\ax \aoCompleted \arSpawnPull \atMainLoop \agCycle:\ax \ao...\ax \agLets do it again !!!\ax
	/message ==================================================================
	/delay 3s
	|------------------------
	/call ForceSpawnStepReset
	/call Go2LastSwarmLoc
	|------------------------

	/goto :MainLoopCycle

	|----------------------------------------------------------------------------------------------
	/if (${Debugging}) /echo Sub SwarmPullStepMove_2 Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: Go2LastSwarmLoc     ( Always Call This to pick up From LastSwarmed_Step )
| --------------------------------------------------------------------------------------------
Sub Go2LastSwarmLoc
	/if (${Debugging}) /echo Sub Go2LastSwarmLoc Entry
	|------------------------------------------------------------------------------------------------------------
	|- READ:  LastSwarmed_Dungeon and LastSwarmed_Step from ini file, to pickup at this point if restarted macro.
	|------------------------------------------------------------------------------------------------------------
	/varset LastSwarmed_Dungeon ${Ini[${IniFileName},Theme,LastSwarmed_Dungeon]}
	/varset LastSwarmed_Step ${Ini[${IniFileName},Theme,LastSwarmed_Step]}
	|-------------------------------------------------------------------------------------------------------
	|/echo \arGo2LastSwarmLoc: \ayLastSwarmed_Dungeon=(${LastSwarmed_Dungeon}) | LastSwarmed_Step=(${LastSwarmed_Step})
	|-------------------------------------------------------------------------------------------------------
	/if (${Debugging}) /echo LastSwarmed_Dungeon=(${LastSwarmed_Dungeon}) | LastSwarmed_Step=(${LastSwarmed_Step})
	/message \agThe last known spawn pull \aySTEP\ag is: \ay[\am${LastSwarmed_Step}\ay]

	|--------------------------------------------------------------------------------------------------------------------------
	| - Call the SwarmPullStepMove function and pass the location and step from INI file
	| - (The Array Values have already defined from DoSwarmPull)
	| -
	| If we are in same dungeon, pickup from LastSwarmed_Loc .. else..  run the path fresh !
	| SwarmPullStepMove will pick up the path in a loop where the step number will change X in the loop !
	|--------------------------------------------------------------------------------------------------------------------------
	|/echo {Zone.ShortName}=(${Zone.ShortName}) | {Ini.File.Zone.Name}=(${LastSwarmed_Dungeon})
	|-----------------------------------------------------------------------
	| Change values to pass STEP 1 if we arent in the last recorded dungeon.
	|-----------------------------------------------------------------------
	/if (!${Zone.ShortName.Equal[${LastSwarmed_Dungeon}]}) {
		/call ForceSpawnStepReset
	}
	|-----------------------------------------------------------------------
	|/echo \arGo2LastSwarmLoc: \ay/call SwarmPullStepMove ${LastSwarmed_Step}
	|-----------------------------------------------------------------------

	|-----------------------------------
	|- Retrieve the last mission results
	|-----------------------------------
	/varset CompletedPathTo ${Ini[${IniFileName},Theme,CompletedPathTo]}
	|-----------------------------------
	/if (!${CompletedPathTo}) {
		/call SwarmPullStepMove_1 ${LastSwarmed_Step}
	} else {
		/call SwarmPullStepMove_2 ${LastSwarmed_Step}
	}
	|-----------------------------------------------------------------------

	|--------------------------------------------------------------------------------------------------------------------------
	/if (${Debugging}) /echo Sub Go2LastSwarmLoc Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------------
| SUB: ForceSpawnStepReset
| --------------------------------------------------------------------------------------------------
Sub ForceSpawnStepReset
/if (${Debugging}) /echo Sub ForceSpawnStepReset Entry
	
	/message \arForcing LastSwarmed_Step reset to step \ay(\at1\ay)
	
	|----------------------------------------------------------
	| -- Write STEP 1 to the ini file since we want to set our initial first step for that zone.
	|------------------------------------------
	/call IniChange "Theme" "LastSwarmed_Step" 1
	/varset LastSwarmed_Step 1
	/delay 20
	|------------------------------------------

/if (${Debugging}) /echo Sub ForceSpawnStepReset Exit
/return
| --------------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: DoSwarmPull_PathTo		Note: Define The Array Variables and kick off Go2LastSwarmLoc
| --------------------------------------------------------------------------------------------
Sub DoSwarmPull_PathTo
/if (${Debugging}) /echo Sub DoSwarmPull_PathTo Entry

/message \agSetting up pathing to \ay[\arSwarm Pull\ay] \agdungeon. . . . .
/message ==================================================================

|---------------------------------------------------------
| Delete any EXISTING LocalStepArray
|---------------------------------------------------------
/if (${Defined[LocalStepArray_${Zone.ShortName}_1]}) {
	/message \arDeleting \atOLD \aydungeon array\ar \am[\atLocalStepArray_${Zone.ShortName}_1\am]\ax
	/deletevar LocalStepArray_${Zone.ShortName}_1
}
|---------------------------------------------------------

|------------------------1: CataCombC
	/message \atLoading steps for: \ay[Catacombs of Dranik (Caza)]\at.
	|------------------------------------------------------
	|  Define The Array Variables so the dungeon can be Run
	|------------------------------------------------------
	|------------------------------------------------------
	/message \ayCreating dynamic dungeon array.
	/if (!${Defined[LocalStepArray_${Zone.ShortName}_1]}) {
		/message \ayCreating \am[\atLocalStepArray_${Zone.ShortName}_1[1,14]\am]\ax
		/declare LocalStepArray_${Zone.ShortName}_1[1,14]	string	outer
		/delay 10
	}
	|------------------------------------------------------

	|---------------------------------- PATH TO MAIN CYCLE
	/varset LocalStepArray_${Zone.ShortName}_1[1,1] -20.83 -82.37 -2.72
	/varset LocalStepArray_${Zone.ShortName}_1[1,2] 199.91 118.39 -53.53
	/varset LocalStepArray_${Zone.ShortName}_1[1,3] 627.67 96.03 -71.11
	/varset LocalStepArray_${Zone.ShortName}_1[1,4] 665.50 -32.93 -73.64
	/varset LocalStepArray_${Zone.ShortName}_1[1,5] 477.28 -42.11 -76.19
	|---------------------------------- 1st large room below
	/varset LocalStepArray_${Zone.ShortName}_1[1,6] 800.04 206.63 -95.55
	/varset LocalStepArray_${Zone.ShortName}_1[1,7] 800.04 400.91 -92.62
	/varset LocalStepArray_${Zone.ShortName}_1[1,8] 800.04 706.04 -92.56
	|---------------------------------- 1st large room above
	/varset LocalStepArray_${Zone.ShortName}_1[1,9] 888.57 -140.53 -114.78
	/varset LocalStepArray_${Zone.ShortName}_1[1,10] 982.44 211.49 -114.78
	|---------------------------------- 2nd large room below
	/varset LocalStepArray_${Zone.ShortName}_1[1,11] 1145.28 22.82 -113.12
	/varset LocalStepArray_${Zone.ShortName}_1[1,12] 1344.02 25.44 -113.35
	|---------------------------------- 2nd large room above
	/varset LocalStepArray_${Zone.ShortName}_1[1,13] 1593.92 193.18 -135.82
	/varset LocalStepArray_${Zone.ShortName}_1[1,14] 1757.71 303.57 -135.19
	|---------------------------------- PATH TO MAIN CYCLE

	|------------------------------------------------------
	/message \ayStep \am[\ag1\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,1]}\am]\ay
	/message \ayStep \am[\ag2\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,2]}\am]\ay
	/message \ayStep \am[\ag3\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,3]}\am]\ay
	/message \ayStep \am[\ag4\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,4]}\am]\ay
	/message \ayStep \am[\ag5\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,5]}\am]\ay
	/message \ayStep \am[\ag6\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,6]}\am]\ay
	/message \ayStep \am[\ag7\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,7]}\am]\ay
	/message \ayStep \am[\ag8\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,8]}\am]\ay
	/message \ayStep \am[\ag9\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,9]}\am]\ay
	/message \ayStep \am[\ag10\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,10]}\am]\ay
	/message \ayStep \am[\ag11\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,11]}\am]\ay
	/message \ayStep \am[\ag12\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,12]}\am]\ay
	/message \ayStep \am[\ag13\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,13]}\am]\ay
	/message \ayStep \am[\ag14\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_1[1,14]}\am]\ay
	/message ==================================================================
	|----------------------------------------------------
	/message \agGet ready, the fun is starting soon !
	/delay 5
	/if (${Me.XTarget}) /call DoClearTargets
	/delay 10
	|--------------- SET CompletedPathTo
	/call IniChange "Theme" "CompletedPathTo" "FALSE"
	/call Go2LastSwarmLoc
	|------------
 }
|------------------------1: CataCombC

/if (${Debugging}) /echo Sub DoSwarmPull_PathTo Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: DoSwarmPull_MainLoop		Note: Define The Array Variables and kick off Go2LastSwarmLoc
| --------------------------------------------------------------------------------------------
Sub DoSwarmPull_MainLoop
/if (${Debugging}) /echo Sub DoSwarmPull_MainLoop Entry

/message \agSetting up pathing to \ay[\arSwarm Pull\ay] \agdungeon. . . . .
/message ==================================================================

|---------------------------------------------------------
| Delete any EXISTING LocalStepArray
|---------------------------------------------------------
/if (${Defined[LocalStepArray_${Zone.ShortName}_2]}) {
	/message \arDeleting \atOLD \aydungeon array\ar \am[\atLocalStepArray_${Zone.ShortName}_2\am]\ax
	/deletevar LocalStepArray_${Zone.ShortName}_2
}
|---------------------------------------------------------

|------------------------1: CataCombC
	/message \atLoading steps for: \ay[Catacombs of Dranik (Caza)]\at.
	|------------------------------------------------------
	|  Define The Array Variables so the dungeon can be Run
	|------------------------------------------------------
	|------------------------------------------------------
	/message \ayCreating dynamic dungeon array.
	/if (!${Defined[LocalStepArray_${Zone.ShortName}_2]}) {
		/message \ayCreating \am[\atLocalStepArray_${Zone.ShortName}_2[1,19]\am]\ax
		/declare LocalStepArray_${Zone.ShortName}_2[1,19]	string	outer
		/delay 10
	}
	|------------------------------------------------------

	|---------------------------------- MAIN CYCLE BELOW
	|---------------------------------- LEFT BOTTOM
	/varset LocalStepArray_${Zone.ShortName}_2[1,1] 2016.83 451.40 -135.32
	/varset LocalStepArray_${Zone.ShortName}_2[1,2] 2016.83 571.16 -135.32
	/varset LocalStepArray_${Zone.ShortName}_2[1,3] 1990.50 748.16 -134.32
	|---------------------------------- LEFT BOTTOM
	|---------------------------------- LEFT MIDDLE
	/varset LocalStepArray_${Zone.ShortName}_2[1,4] 2247.83 451.40 -135.32
	/varset LocalStepArray_${Zone.ShortName}_2[1,5] 2188.26 582.50 -134.43
	/varset LocalStepArray_${Zone.ShortName}_2[1,6] 2247.83 711.16 -135.32
	|---------------------------------- LEFT MIDDLE
	|---------------------------------- LEFT TOP
	/varset LocalStepArray_${Zone.ShortName}_2[1,7] 2449.70 451.40 -135.32
	/varset LocalStepArray_${Zone.ShortName}_2[1,8] 2449.70 571.16 -135.32
	/varset LocalStepArray_${Zone.ShortName}_2[1,9] 2449.70 711.16 -135.32
	|---------------------------------- LEFT TOP
	|---------------------------------- RIGHT TOP
	/varset LocalStepArray_${Zone.ShortName}_2[1,10] 2417.39 231.31 -134.91
	/varset LocalStepArray_${Zone.ShortName}_2[1,11] 2449.70 91.40 -135.32
	/varset LocalStepArray_${Zone.ShortName}_2[1,12] 2497.22 -81.97.40 -134.72
	|---------------------------------- RIGHT TOP
	|---------------------------------- RIGHT MIDDLE
	/varset LocalStepArray_${Zone.ShortName}_2[1,13] 2228.83 251.40 -135.32
	/varset LocalStepArray_${Zone.ShortName}_2[1,14] 2228.83 91.40 -135.32
	/varset LocalStepArray_${Zone.ShortName}_2[1,15] 2282.11 -93.10 -132.69
	|---------------------------------- RIGHT MIDDLE
	|---------------------------------- RIGHT BOTTOM
	/varset LocalStepArray_${Zone.ShortName}_2[1,16] 2007.83 251.40 -135.32
	/varset LocalStepArray_${Zone.ShortName}_2[1,17] 2007.83 91.40 -135.32
	/varset LocalStepArray_${Zone.ShortName}_2[1,18] 1975.42 -58.06 -133.82
	|---------------------------------- RIGHT BOTTOM
	|---------------------------------- MAIN CYCLE ABOVE
	
	|---------------------------------- PrCamp
	/varset LocalStepArray_${Zone.ShortName}_2[1,19] 1707.48 270.58 -132.80
	|---------------------------------- PrCamp

	|------------------------------------------------------
	/message \ayStep \am[\ag1\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,1]}\am]\ay
	/message \ayStep \am[\ag2\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,2]}\am]\ay
	/message \ayStep \am[\ag3\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,3]}\am]\ay
	/message \ayStep \am[\ag4\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,4]}\am]\ay
	/message \ayStep \am[\ag5\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,5]}\am]\ay
	/message \ayStep \am[\ag6\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,6]}\am]\ay
	/message \ayStep \am[\ag7\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,7]}\am]\ay
	/message \ayStep \am[\ag8\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,8]}\am]\ay
	/message \ayStep \am[\ag9\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,9]}\am]\ay
	/message \ayStep \am[\ag10\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,10]}\am]\ay
	/message \ayStep \am[\ag11\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,11]}\am]\ay
	/message \ayStep \am[\ag12\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,12]}\am]\ay
	/message \ayStep \am[\ag13\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,13]}\am]\ay
	/message \ayStep \am[\ag14\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,14]}\am]\ay
	/message \ayStep \am[\ag15\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,15]}\am]\ay
	/message \ayStep \am[\ag16\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,16]}\am]\ay
	/message \ayStep \am[\ag17\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,17]}\am]\ay
	/message \ayStep \am[\ag18\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,18]}\am]\ay
	/message \ayStep \am[\ag19\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,19]}\am]\ay
	/message ==================================================================
	|----------------------------------------------------
	/message \agGet ready, the fun is starting soon !
	/delay 5
	/if (${Me.XTarget}) /call DoClearTargets
	/delay 10
	|- Call Go2LastSwarmLoc after Defining Array
	/call Go2LastSwarmLoc
	|------------
 }
|------------------------1: CataCombC

/if (${Debugging}) /echo Sub DoSwarmPull_MainLoop Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: DoSwarmPull_MainLoop_Bigger		Note: Define The Array Variables and kick off Go2LastSwarmLoc
| --------------------------------------------------------------------------------------------
Sub DoSwarmPull_MainLoop_Bigger
/if (${Debugging}) /echo Sub DoSwarmPull_MainLoop_Bigger Entry

/message \agSetting up pathing to \ay[\arSwarm Pull\ay] \agdungeon. . . . .
/message ==================================================================

|---------------------------------------------------------
| Delete any EXISTING LocalStepArray
|---------------------------------------------------------
/if (${Defined[LocalStepArray_${Zone.ShortName}_2]}) {
	/message \arDeleting \atOLD \aydungeon array\ar \am[\atLocalStepArray_${Zone.ShortName}_2\am]\ax
	/deletevar LocalStepArray_${Zone.ShortName}_2
}
|---------------------------------------------------------

|------------------------1: CataCombC
	/message \atLoading steps for: \ay[Catacombs of Dranik (Caza)]\at.
	|------------------------------------------------------
	|  Define The Array Variables so the dungeon can be Run
	|------------------------------------------------------
	|------------------------------------------------------
	/message \ayCreating dynamic dungeon array.
	/if (!${Defined[LocalStepArray_${Zone.ShortName}_2]}) {
		/message \ayCreating \am[\atLocalStepArray_${Zone.ShortName}_2[1,9]\am]\ax
		/declare LocalStepArray_${Zone.ShortName}_2[1,9]	string	outer
		/delay 10
	}
	|------------------------------------------------------

	|---------------------------------- MAIN CYCLE BELOW
	|---------------------------------- LEFT BOTTOM
	/varset LocalStepArray_${Zone.ShortName}_2[1,1] 2016.83 711.16 -135.32
	|---------------------------------- LEFT BOTTOM
	|---------------------------------- LEFT MIDDLE
	/varset LocalStepArray_${Zone.ShortName}_2[1,2] 2247.83 711.16 -135.32
	|---------------------------------- LEFT MIDDLE
	|---------------------------------- LEFT TOP
	/varset LocalStepArray_${Zone.ShortName}_2[1,3] 2449.70 711.16 -135.32
	|---------------------------------- LEFT TOP
	|---------------------------------- RIGHT TOP
	/varset LocalStepArray_${Zone.ShortName}_2[1,4] 2447.29 -98.40 -134.32
	|---------------------------------- RIGHT TOP
	|---------------------------------- RIGHT MIDDLE
	/varset LocalStepArray_${Zone.ShortName}_2[1,5] 2213.83 -96.62 -134.22
	|---------------------------------- RIGHT MIDDLE
	|---------------------------------- RIGHT BOTTOM
	/varset LocalStepArray_${Zone.ShortName}_2[1,6] 1983.36 -75.24 -132.90
	|---------------------------------- RIGHT BOTTOM
	|---------------------------------- MAIN CYCLE ABOVE
	
	|---------------------------------- PrCamp
	/varset LocalStepArray_${Zone.ShortName}_2[1,7] 1707.48 270.58 -132.80
	|---------------------------------- PrCamp	
	
	|---------------------------------- PrCamp-1
	/varset LocalStepArray_${Zone.ShortName}_2[1,8] 1821.42 7.47 -133.12
	|---------------------------------- PrCamp-1
	
	|---------------------------------- PrCamp-2 (Signets)
	/varset LocalStepArray_${Zone.ShortName}_2[1,9] 1140.00 -85.00 -111.37
	|---------------------------------- PrCamp-2 (Signets)	
	
	|------------------------------------------------------
	/message \ayStep \am[\ag1\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,1]}\am]\ay
	/message \ayStep \am[\ag2\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,2]}\am]\ay
	/message \ayStep \am[\ag3\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,3]}\am]\ay
	/message \ayStep \am[\ag4\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,4]}\am]\ay
	/message \ayStep \am[\ag5\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,5]}\am]\ay
	/message \ayStep \am[\ag6\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,6]}\am]\ay
	/message \ayStep \am[\ag7\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,7]}\am]\ay	
	/message \ayStep \am[\ag8\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,8]}\am]\ay
	/message \ayStep \am[\ag9\am]\ay set to \am[\ag${LocalStepArray_${Zone.ShortName}_2[1,9]}\am]\ay	
	/message ==================================================================
	|----------------------------------------------------
	/message \agGet ready, the fun is starting soon !
	/delay 5
	/if (${Me.XTarget}) /call DoClearTargets
	/delay 10
	|- Call Go2LastSwarmLoc after Defining Array
	/call Go2LastSwarmLoc
	|------------
 }
|------------------------1: CataCombC

/if (${Debugging}) /echo Sub DoSwarmPull_MainLoop_Bigger Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: NavToLoc -- [NO Combat and Agro Aware movement]
| --------------------------------------------------------------------------------------------
Sub NavToLoc(int Y,int X,int Z)
	/if (${Debugging}) /echo Entering Sub NavToLoc for ${Y} ${X} ${Z} at Line: ${Macro.CurLine}
	/varset GroupWaitTimer 0
	/message \at-- NavToLoc \ay[\amNo Combat & Agro aware movement\ay] \atto \ay[\am${Y} ${X} ${Z}\ay]\at.
	|-------------------------------------------------------------------------------
	/while (${Math.Distance[${Me.Y}, ${Me.X}, ${Me.Z}: ${Y}, ${X}, ${Z}]} > 30) {
		/if (${Navigation.Active}) {
			/if (${CheckBots}) /call GroupDeathChk
			/if (${CheckBots}) /call GroupManaChk
			/if (${CheckBots}) /call GroupEndChk
			/call GMCheck
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) {
				/if (${Navigation.Active}) /nav stop
				/if (${Debugging}) /echo CALL DoSinglePull NavToLoc
				/call DoSinglePull
			} else {
				/if (${CheckBots}) /call GroupDeathChk
				/if (${CheckBots}) /call GroupManaChk
				/if (${CheckBots}) /call GroupEndChk
				/call GMCheck
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/delay 10
		} else {
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) {
				/if (${Navigation.Active}) /nav stop
				/if (${Debugging}) /echo CALL FARM STUFF NavToLoc II
				/call DoSinglePull
			} else {
				/if (${CheckBots}) /call GroupDeathChk
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/if (!${Me.Combat} && !${Me.XTarget}) /call Group2Me
			/if (!${Me.Moving}) /squelch /e3bcgza /nav loc ${Y} ${X} ${Z}
			/delay 5 ${Me.Moving}
			/delay 5 ${Navigation.Active}
		}
	}
	|-------------------------------------------------------------------------------
	/delay 2s
	/if (${Navigation.Active}) /nav stop
	/if (${Debugging}) /echo Sub NavToLoc Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: NavToLoc2 -- [Combat and Agro Aware movement]
| --------------------------------------------------------------------------------------------
Sub NavToLoc2(int Y,int X,int Z)
	/if (${Debugging}) /echo Entering Sub NavToLoc2 for ${Y} ${X} ${Z} at Line: ${Macro.CurLine}
	/varset GroupWaitTimer 0
	/message \at-- NavToLoc2 \ay[\amCombat & Agro aware movement\ay] \atto \ay[\am${Y} ${X} ${Z}\ay]\at.
	/while (${Math.Distance[${Me.Y}, ${Me.X}, ${Me.Z}: ${Y}, ${X}, ${Z}]} > 20) {
		/if (${Navigation.Active}) {
			/if (${Debugging}) /echo WaitNav Moving ELSE
			/if (${CheckBots}) /call GroupDeathChk
			/if (${CheckBots}) /call GroupManaChk
			/if (${CheckBots}) /call GroupEndChk
			/call GMCheck
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) {
				/popcustom 13 5 ---> GOT AGGRO ON ROUTE <---
				/if (${Navigation.Active}) /nav stop
				/if (${Debugging}) /echo CALL DoSinglePull NavToLoc						
				/target id ${NearestSpawn[npc radius 35 targetable].ID}
				/if (${Spawn[id ${Target.ID}].Distance} > 30) /squelch /nav id ${Target.ID}
				/if (${Spawn[id ${Target.ID}].Distance} < 30) {
					|------  CALL GROUP TO ME To FIGHT
					/call Group2Me
					|------  CALL GROUP TO ME To FIGHT	
					/if (${Target.ID}) /face
					/squelch /attack on
					/call DoClearTargets			
					/if (${LootCorpse} && !${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /call CheckForCorpses
					/doevents
					/if (${UseClickDamage}) /call Clickies_Damage
				}
			} else {
				/if (${Debugging}) /echo WaitNav Moving ELSE
				/if (${CheckBots}) /call GroupDeathChk
				/if (${CheckBots}) /call GroupManaChk
				/if (${CheckBots}) /call GroupEndChk
				/call GMCheck
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/delay 10
		} else {
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) {
				/popcustom 13 5 ---> GOT AGGRO ON ROUTE <---
				/if (${Navigation.Active}) /nav stop
				/if (${Debugging}) /echo CALL FARM STUFF NavToLoc II
				/target id ${NearestSpawn[npc radius 35 targetable].ID}
				/if (${Spawn[id ${Target.ID}].Distance} > 30) /squelch /nav id ${Target.ID}
				/if (${Spawn[id ${Target.ID}].Distance} < 30) {
					|------  CALL GROUP TO ME To FIGHT
					/call Group2Me
					|------  CALL GROUP TO ME To FIGHT					
					/if (${Target.ID}) /face
					/squelch /attack on
					/call DoClearTargets			
					/if (${LootCorpse} && !${Me.XTarget} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /call CheckForCorpses
					/doevents
					/if (${UseClickDamage}) /call Clickies_Damage
				}
			} else {
				/if (${CheckBots}) /call GroupDeathChk
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/if (!${Me.Moving} && !${Me.Combat} && !${Me.XTarget}) /squelch /e3bcgza /nav loc ${Y} ${X} ${Z}
			/delay 5 ${Me.Moving}
			/delay 5 ${Navigation.Active}
		}
	}
	/delay 2s
	/if (${Navigation.Active}) /nav stop
	/if (${Debugging}) /echo Sub NavToLoc2 Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: NavToLoc3 - [Combat and Agro Aware movement - with invis recheck]
| --------------------------------------------------------------------------------------------
Sub NavToLoc3(int Y,int X,int Z)
	/if (${Debugging}) /echo Entering Sub NavToLoc3 for ${Y} ${X} ${Z} at Line: ${Macro.CurLine}
	/varset GroupWaitTimer 0
	/message \at-- NavToLoc3 \ay[\amCombat and Agro Aware movement - with invis recheck\ay] \atto \ay[\am${Y} ${X} ${Z}\ay]\at.
	/while (${Math.Distance[${Me.Y}, ${Me.X}, ${Me.Z}: ${Y}, ${X}, ${Z}]} > 20) {
		/if (${Navigation.Active}) {
			/if (${Debugging}) /echo WaitNav Moving ELSE
			/if (${CheckBots}) /call GroupDeathChk
			/if (${CheckBots}) /call GroupManaChk
			/if (${CheckBots}) /call GroupEndChk
			/call GMCheck
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) {
				/if (${Navigation.Active}) /nav stop
				/if (${Debugging}) /echo CALL DoSinglePull NavToLoc
				|------  CALL GROUP TO ME To FIGHT
				/call Group2Me
				|------  CALL GROUP TO ME To FIGHT				
				/target id ${NearestSpawn[npc radius 35 targetable].ID}
				/if (${Spawn[id ${Target.ID}].Distance} > 30) /squelch /nav id ${Target.ID}
				/if (${Spawn[id ${Target.ID}].Distance} < 30) {
					/if (${Target.ID}) /face
					/squelch /attack on
					/call Group2Me
					/call DoClearTargets
					/doevents
					/if (${UseClickDamage}) /call Clickies_Damage
				}
			} else {
				/if (${Debugging}) /echo WaitNav Moving ELSE
				/if (${CheckBots}) /call GroupDeathChk
				/if (${CheckBots}) /call GroupManaChk
				/if (${CheckBots}) /call GroupEndChk
				/call GMCheck
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/delay 10
		} else {
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) {
				/if (${Navigation.Active}) /nav stop
				/if (${Debugging}) /echo CALL FARM STUFF NavToLoc II
				|------  CALL GROUP TO ME To FIGHT
				/call Group2Me
				|------  CALL GROUP TO ME To FIGHT				
				/target id ${NearestSpawn[npc radius 35 targetable].ID}
				/if (${Spawn[id ${Target.ID}].Distance} > 30) /squelch /nav id ${Target.ID}
				/if (${Spawn[id ${Target.ID}].Distance} < 30) {
					/if (${Target.ID}) /face
					/squelch /attack on
					/call Group2Me
					/call DoClearTargets
					/doevents
					/if (${UseClickDamage}) /call Clickies_Damage
				}
			} else {
				/if (${CheckBots}) /call GroupDeathChk
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/if (!${Me.Combat} && !${Me.XTarget} && ${DoInvis}) /call CheckInvis
			/if (!${Me.Moving} && !${Me.Combat} && !${Me.XTarget} && ${Me.Invis}) /squelch /e3bcgza /nav loc ${Y} ${X} ${Z}
			/delay 5 ${Me.Moving}
			/delay 5 ${Navigation.Active}
		}
	}
	/delay 2s
	/if (${Navigation.Active}) /nav stop
	/if (${Debugging}) /echo Sub NavToLoc3 Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: WaitNav
| --------------------------------------------------------------------------------------------
Sub WaitNav(NavTargetID)
	/if (${Debugging}) /echo \agEntering Sub WaitNav for ${Spawn[id ${NavTargetID}].Y} ${Spawn[id ${NavTargetID}].X} ${Spawn[id ${NavTargetID}].Z} at Line: ${Macro.CurLine}
	/message \at-- WaitNav \ay[\amCombat & Agro aware STAGGERED movement\ay] \atto mob id:\ay[\am${NavTargetID}\ay]\at.
	/if (!${Spawn[id ${NavTargetID}].ID}) {
		/delay 5s
		/return
	}
	/while (${Spawn[id ${NavTargetID}].Distance} > 30 || !${Spawn[${myTargetID}].LineOfSight}) {
		/if (!${Spawn[id ${NavTargetID}].ID}) {
			/delay 5s
			/return
		}
		/if (${Spawn[id ${NavTargetID}].Distance} < 30) {
			/nav stop
		}
		/if (${Spawn[id ${NavTargetID}].ID}) {
			/call SetLoc
			/call CheckStuck
			/call GMCheck
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) {
				/if (${Navigation.Active}) /nav stop
				/varset NavTargetID ${NearestSpawn[npc radius 35 targetable].ID}
				/if (${Debugging}) /echo CALL DoSinglePull WaitNav I
				/call DoSinglePull
			} else {
				/if (${Debugging}) /echo \ayWaitNav Moving
				/if (${CheckBots}) /call GroupDeathChk
				/if (${CheckBots}) /call GroupManaChk
				/if (${CheckBots}) /call GroupEndChk
				/call GMCheck
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/if (!${courseCorrection}) {
				|------  ALL GO TO TARGET - staggered
				/nav id ${NavTargetID}
				/delay 5
				/squelch /e3bcgz /nav id ${NavTargetID}
				|------  ALL GO TO TARGET - staggered
				/varset courseCorrection ${courseCorrection.OriginalValue}
			}
			|----------------------------------
			| Should group come to me on pulls. 
			|----------------------------------
			/if (${GroupNavToMe}) {
                /call Group2Me
            }
			|----------------------------------
			/delay 10
		} else {
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 35].Aggressive}]}) {
				/if (${Navigation.Active}) /nav stop
				/e3bcgza /target id ${NearestSpawn[npc radius 35 targetable].ID}
				/varset NavTargetID ${NearestSpawn[npc radius 35 targetable].ID}
				/if (${Debugging}) /echo CALL DoSinglePull WaitNav II
				/call DoSinglePull
			} else {
				/varcalc BackUpTimer (${BackUpTimer})+1
				/if (${BackUpTimer}>7) {
					/message \ayHaving trouble getting to a target.. Attempting to get back on mesh.
					/if (${Debugging}) /echo Setting BackUpTimer Plus 1
					/call BackUp
					/varset BackUpTimer 0
					/varset NavTargetID 0
					/if (${Me.XTarget}) {
						/varset NavTargetID ${Me.XTarget}
					}
				}
				/if (${Debugging}) /echo WaitNav Moving ELSE
				/if (${CheckBots}) /call GroupDeathChk
				/if (${CheckBots}) /call GroupManaChk
				/if (${CheckBots}) /call GroupEndChk
			}
			/if (${Me.Combat} && !${Me.XTarget}) /squelch /target clear
			/squelch /nav id ${NavTargetID}
		}
	}
	/if (${Navigation.Active}) /nav stop
	:target
	/target id ${NavTargetID}
	/delay 2s ${Target.CleanName.Equal[${Spawn[id ${NavTargetID}].CleanName}]}
	/if (!${Target.CleanName.Equal[${Spawn[id ${NavTargetID}].CleanName}]} && ${Spawn[id ${NavTargetID}].ID} && !${Me.XTarget}) {
		/goto :target
	}
	/if (${Debugging}) /echo Sub WaitNav Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: Zoning
| --------------------------------------------------------------------------------------------
Sub Zoning
	/if (${Debugging}) /echo Sub Zoning Entry
	:Zoning
	/delay 2m ${Zone.ID}!=${startZone}
	/target id ${Me.ID}
	/delay 1s ${Target.ID}==${Me.ID}
	/if (!${Navigation.MeshLoaded}) {
		/message \ayWaiting for you to load a mesh for this zone.
		/nav reload
		/delay 5s
		/goto :Zoning
	}
	/delay 2s
	/varset startZone ${Zone.ID}
	/squelch /target clear
	/call CheckMesh
	/delay 2s
	|---------------------------------------------
	| Cleartargets if I have agro on zoning.
	|---------------------------------------------
	/if (${Me.XTarget}) /Call DoClearTargets
	/call Refresh
	/if (${Debugging}) /echo Sub Zoning Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: CheckForCorpses
| --------------------------------------------------------------------------------------------
  Sub CheckForCorpses
  /if (${Debugging}) /echo Sub CheckForCorpses Entry

  /call GMCheck
  /message \ay- Checking for missed corpse(s).
  /if (${Bool[${Spawn[Corpse radius 75]}]}) /message \at+++ \ayLooks like we have a corpse to loot.
  /if (${Target.ID} && (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]})) /squelch /target clear
  
:CheckAgain
  |------------------
  /if (${MouseLock}) /mouseto ${MouseLocValX}, ${MouseLocValY}
  |------------------
  |/hidecorpse looted
  /hidecorpse none
  |------------------

  /squelch /target radius 75 corpse
  /delay 5 ${Target.ID}
	
	|----------------------------------------------
	/if (${Target.ID} && ${Target.Type.Equal[Corpse]}) {
		/face fast nolook

		|----------------------------------------------
		|-----
		:MoveToCorpse
		|/echo DEBUG: (MoveToCorpse) CORPSE CODE START
		/if (${Navigation.PathExists[id ${Target.ID}]}) {
			/if (${Target.ID} && ${Target.Type.Equal[Corpse]} && (${Target.Distance}>10) && !${Me.Casting.ID}) /nav id ${Target.ID}
			|/echo DEBUG: (NAV) TO CORPSE CODE - TargetDistance=(${Target.Distance})
		} else {
			/if (${Target.ID} && ${Target.Type.Equal[Corpse]} && (${Target.Distance}>10) && !${Me.Casting.ID}) /moveto id ${Target.ID} mdist 10
			|/echo DEBUG: (MOVE) TO CORPSE CODE - TargetDistance=(${Target.Distance})
		}
		/delay 1s ${Target.Distance}<=10
		/if (${Target.ID} && ${Target.Type.Equal[Corpse]} && (${Target.Distance}>10) && !${Me.Casting.ID}) /goto :MoveToCorpse
		|/echo DEBUG: (MoveToCorpse) CORPSE CODE END
		|-----
		|----------------------------------------------

		|-------------------------
		/call CheckCasting
		/delay 5 !${Me.Moving}	
		/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 50].Aggressive}]}) /call DoClearTargets	
		|--------------------------------------------------------------------------------
		/if (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]} && !${Me.Casting.ID} && !${Me.Moving} && ${LootMethod.Equal[DCONLY]}) /call LootMob_DC_Only
		/if (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]} && !${Me.Casting.ID} && !${Me.Moving} && ${LootMethod.Equal[E3]}) /call LootMob_E3
		/if (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]} && !${Me.Casting.ID} && !${Me.Moving} && ${LootMethod.Equal[TURBOLOOT]}) /call LootMob_Turboloot
		/delay 5
		|--------------------------------------------------------------------------------
	}
    /squelch /target clear
	|-------------------------
	/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 50].Aggressive}]}) /call DoClearTargets	
    /if (${Bool[${Spawn[Corpse radius 75]}]}) /goto :CheckAgain
  } else {
    /message \ar+++ \ayNo corpse(s) found to loot.\ax
  }

	/if (${Debugging}) /echo Sub CheckForCorpses Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: LootMob_Turboloot -- Let Turboloot Looting handle your corpseloot.
| --------------------------------------------------------------------------------------------
  Sub LootMob_Turboloot
	/if (${Debugging}) /echo Sub LootMob_Turboloot Entry		

	|---------------------------------------
	| -- Let TURBOLOOT Looting System handle this !
	|---------------------------------------
	/if (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]}) {
		/message \at+++ \ayHaving \am[\ag${TurboLooter}\am]\ay loot via \am[\aoTurboLoot\am]\ay.		
		/message \at+ \aoHiding corpse(s) from myself.
		/hidecorpse all
		/squelch /e3bct ${TurboLooter} /mac TurboLoot
		/message \at+ \aoWaiting on \am[\ag${TurboLooter}\am]\ay to finish looting.
		/varset TurboLootPause TRUE
		/delay 5
		|---------------------------
		/while (${TurboLootPause}) {			
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 50].Aggressive}]}) /call DoClearTargets			
			/doevents
			/delay 1s
		}
		|---------------------------
		/message \at+++ \ayDone having \am[\ag${TurboLooter}\am]\ay loot via \am[\aoTurboLoot\am]\ay.
	} else {
		/call DoClearTargets
	}
	|---------------------------------------
	| -- Let TURBOLOOT Looting System handle this !
	|---------------------------------------
	|--------------------------------------------
	/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 50].Aggressive}]}) /call DoClearTargets
	|--------------------------------------------
	/doevents
	|-------------------------------------------------------------------------------------

	/if (${Debugging}) /echo Sub LootMob_Turboloot Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: LootMob_E3 -- Let E3 Looting handle your corpseloot.
| --------------------------------------------------------------------------------------------
  Sub LootMob_E3
	/if (${Debugging}) /echo Sub LootMob_E3 Entry

	/if (${Target.ID} && ${Target.Type.Equal[Corpse]}) /face fast nolook
	/keypress forward
	/keypress back
	/fastdrop on
	/lootn never
	
	|---------------------------------------
	| -- HANDLE CONDITIONALY !
	|---------------------------------------
	 /if (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]}) {
		/message \at+++ \ayLooting - \ag Corpse\ao: \ar[\am${Target.CleanName}\ar] \agID\ao: \ar[\am${Target.ID}\ar].
		/loot
	} else {
		/call DoClearTargets
	}
	|---------------------------------------
	| -- HANDLE CONDITIONALY !
	|---------------------------------------
	|--------------------------------------------
	/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 50].Aggressive}]}) /call DoClearTargets
	|--------------------------------------------
	/doevents
	|-------------------------------------------------------------------------------------
	/if (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]}  && !${Me.Casting.ID} && !${Me.Moving}) /call CheckIfBagsFull
	|-------------------------------------------------------------------------------------

	/if (${Debugging}) /echo Sub LootMob_E3 Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: DranikCLootArraySetup
| --------------------------------------------------------------------------------------------
  Sub DranikCLootArraySetup
    /if (${Debugging}) /echo Sub DranikCLootArraySetup Entry
	|----------------------------------------------------------
	/varset DranikCLootArray[1,1] Black Pearl
	/varset DranikCLootArray[1,2] Blue Diamond
	/varset DranikCLootArray[1,3] Broken Ukun Leash
	/varset DranikCLootArray[1,4] Congealed Bat Blood
	/varset DranikCLootArray[1,5] Cracked Stone Eye
	/varset DranikCLootArray[1,6] Curled Rat Foot
	/varset DranikCLootArray[1,7] Diamond
	/varset DranikCLootArray[1,8] Diamond Coin
	/varset DranikCLootArray[1,9] Dragorn Claw
	/varset DranikCLootArray[1,10] Dragorn Eye
	/varset DranikCLootArray[1,11] Dragorn Fang
	/varset DranikCLootArray[1,12] Dragorn Wing Bones
	/varset DranikCLootArray[1,13] Emerald
	/varset DranikCLootArray[1,14] Fire Emerald
	/varset DranikCLootArray[1,15] Gnarled Rat Tail
	/varset DranikCLootArray[1,16] Murkglider Sinew
	/varset DranikCLootArray[1,17] Murkglider Stomach
	/varset DranikCLootArray[1,18] Noc Claw
	/varset DranikCLootArray[1,19] Noc Heart
	/varset DranikCLootArray[1,20] Opal
	/varset DranikCLootArray[1,21] Ruby
	/varset DranikCLootArray[1,22] Sapphire
	/varset DranikCLootArray[1,23] Shattered Bat Fang
	/varset DranikCLootArray[1,24] Shattered Visage
	/varset DranikCLootArray[1,25] Shimmering Ukun Hide
	/varset DranikCLootArray[1,26] Sleek Bat Fur
	/varset DranikCLootArray[1,27] Sparse Rat Fur
	/varset DranikCLootArray[1,28] Splintered Bone Necklace
	/varset DranikCLootArray[1,29] Starflow Stone
	/varset DranikCLootArray[1,30] Stone Shard
	/varset DranikCLootArray[1,31] Tattered Ikaav Braid
	/varset DranikCLootArray[1,32] Torn Rat Ear
	/varset DranikCLootArray[1,33] Ukun Guts
	/varset DranikCLootArray[1,34] Wiry Rat Whiskers
	/varset DranikCLootArray[1,35] Stolen Dragorn Clan Insignia
	/varset DranikCLootArray[1,36] Stuffed Christmas Stocking
	/varset DranikCLootArray[1,37] Spell: Mana Weave
	|--------------------------------------------
	/if (${LootTradeMats}) {
		/varset DranikCLootArray[1,38] Rhenium Ore
		/varset DranikCLootArray[1,39] Tungsten Ore
		/varset DranikCLootArray[1,40] Cobalt Ore
		|--------------------------------------------
		/varset DranikCLootArray[1,41] Fine Silk
		/varset DranikCLootArray[1,42] Superb Silk
		/varset DranikCLootArray[1,43] Excellent Silk
		|--------------------------------------------
		/varset DranikCLootArray[1,44] Excellent Animal Pelt
		/varset DranikCLootArray[1,45] Superb Animal Pelt	
	}
	|--------------------------------------------
	/if (${Debugging}) /echo Sub DranikCLootArraySetup Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: LootMob_DC_Only: Standard coin and Diamond Coin
| --------------------------------------------------------------------------------------------
  Sub LootMob_DC_Only
    /if (${Debugging}) /echo Sub LootMob_DC_Only Entry
	
	/declare x  		 			int inner	1
	/declare LootSlot    			int inner	0
    /declare LootCheck  			int inner	0
    /declare LootTotal   			int inner	0
	/declare CursorItemValueInPlat	int inner	0

	/if (${Target.ID} && ${Target.Type.Equal[Corpse]}) /face fast nolook
    /keypress forward
    /keypress back
    /fastdrop on
    /lootn never

	|---------------------------------------
	| -- HANDLE CONDITIONALY !
	|---------------------------------------
	 /if (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]}) {
		/message \at+++ \ayLooting - \ag Corpse\ao: \ar[\am${Target.CleanName}\ar] \agID\ao: \ar[\am${Target.ID}\ar].
		/loot
	} else {
		/call DoClearTargets
	}
	|---------------------------------------
	| -- HANDLE CONDITIONALY !
	|---------------------------------------

	|-------------------------------------
    /delay 1s ${Window[LootWnd].Open}
    /doevents
	|-------------------------------------
	| KEEP DELAY TO POPULATE CORPPSE ITEMS
	|-------------------------------------

	|--------------------------------------
	/if (${Corpse.Items}) {
		/varset LootTotal ${Corpse.Items}
		/message \ay++ Corpse has (\at${LootTotal}\ay) item(s) on it to loot.
		|---------------------------------------
		/for LootSlot 1 to ${LootTotal}
			/if (${Me.XTarget}) /call DoClearTargets
			/message \ay-- Grabbing corpse item (\am${LootSlot}\ax) of (\am${LootTotal}\ax).
			/nomodkey /shift /itemnotify Loot${LootSlot} leftmouseup
			/delay 5 ${Cursor.ID}
			/if (${Window[QuantityWnd].Open}) /notify QuantityWnd QTYW_Accept_Button leftmouseup
			/delay 5

			|----------------------------------------------------------------------------------------------
			/varset CursorItemValueInPlat ${Math.Calc[${FindItem[=${Cursor.Name}].Value}/1000]}
			|----------------------------------------------------------------------------------------------
			
			|/echo (${Cursor.Name}) -- CursorItemValueInPlat=(${CursorItemValueInPlat}) | {MinItemValue})=${MinItemValue})			
						
			|----------------------------------------------------------------------------------------------
			|/echo Starting: LOOT
			|----------------------------------------------------------------------------------------------
			/for x 1 to ${DranikCLootArray.Size}
				|/echo \ayChecking (\am${Cursor.Name}\ay) against (\am${DranikCLootArray[1,${x}]}\ay)
			
				|--------------------------------------------------------
				|---- ALL VALUABLE STACKABLE LOOT THAT DROPS IN THIS ZONE
				|--------------------------------------------------------			
				/if (${Cursor.ID}) {			
					/if (${Cursor.Name.Equal[Diamond Coin]}) {
						/message \at+\ax \agKeeping a\ax \ay(\atDiamond Coin\ay) \ag worth \ay(\at${CursorItemValueInPlat}\ay)\ag platinum ... WOOT!\ax
						/autoinventory 
						/delay 5 !${Cursor.ID}	
					} else /if (${Cursor.Name.Equal[${DranikCLootArray[1,${x}]}]}) {
						/message \at+\ax \agKeeping a\ax \ay(\at${Cursor.Name}\ay) \ag worth \ay(\at${CursorItemValueInPlat}\ay)\ag platinum ... WOOT!\ax
						/autoinventory 
						/delay 5 !${Cursor.ID}
						/varset x ${DranikCLootArray.Size}
					}
				}
				|--------------------------------------------------------			
			/next x
			|----------------------------------------------------------------------------------------------
			|/echo Endiung: LOOT
			|----------------------------------------------------------------------------------------------
			/if (${Me.XTarget} || ${Bool[${Spawn[npc radius 50].Aggressive}]}) /call DoClearTargets	
			|--------------------------------------------------------
			|---- DESTROY ANYTHING REMAINING
			|--------------------------------------------------------
			/if (${Cursor.ID}) {
				/message \ar-\ax \arDestroying a\ax \ay(\at${Cursor.Name}\ay)\ar ...\ax
				|---------------------------------------
				/destroy
				/delay 5 !${Cursor.ID}
				/varset x ${DranikCLootArray.Size}				
			}
			|--------------------------------------------------------
		/doevents
		|--------------------------------------------
		 /if (${Me.XTarget} || ${Bool[${Spawn[npc radius 50].Aggressive}]}) /call DoClearTargets
		|--------------------------------------------
		/next LootSlot
		|---------------------------------------
    }
    |--------------------------------------
    /notify LootWnd DoneButton leftmouseup
    /delay 1s !${Window[LootWnd].Open}
	|--------------------------------------------
    /if (${Me.XTarget} || ${Bool[${Spawn[npc radius 50].Aggressive}]}) /call DoClearTargets
    |--------------------------------------------
    /doevents
    |-------------------------------------------------------------------------------------
    /if (!${Me.XTarget} && !${Bool[${Spawn[npc radius 50].Aggressive}]}  && !${Me.Casting.ID} && !${Me.Moving}) /call CheckIfBagsFull
    |-------------------------------------------------------------------------------------

  /if (${Debugging}) /echo Sub LootMob_DC_Only Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: OpenPacks
| --------------------------------------------------------------------------------------------
	Sub OpenPacks
	/declare bag int local 0
	/if (!${Window[InventoryWindow].Open}) /nomodkey /keypress inventory
	/delay 3s ${Window[InventoryWindow].Open}
	/for bag 1 to 10
		/if (!${Window[Pack${bag}].Open}) /nomodkey /itemnotify pack${bag} rightmouseup
		/delay 3s ${Window[Pack${bag}].Open}
		/if (${Window[TradeskillWnd].Open}) /nomodkey /notify TradeskillWnd ExperimentButton leftmouseup
		/delay 5s !${Window[TradeskillWnd].Open}
	/next bag
	/return
|--------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: ClosePacks
| --------------------------------------------------------------------------------------------
	Sub ClosePacks
	/declare bag int local 0
	/if (!${Window[InventoryWindow].Open}) /nomodkey /keypress inventory
	/delay 3s ${Window[InventoryWindow].Open}
	/for bag 1 to 10
		/if (${Window[Pack${bag}].Open}) /nomodkey /itemnotify pack${bag} rightmouseup
		/delay 3s !${Window[Pack${bag}].Open}
	/next bag
	/if (${Window[InventoryWindow].Open}) /nomodkey /keypress inventory
	/delay 3s !${Window[InventoryWindow].Open}
  /return
|--------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: DoorClick
| --------------------------------------------------------------------------------------------
Sub DoorClick
/if (${Debugging}) /echo Sub DoorClick Entry
	/doortarget
	/delay 1s
	/click left door
/if (${Debugging}) /echo Sub DoorClick Exit
/return
| --------------------------------------------------------------------------------------------

|--------------------------------------------------------
|Group2Me
|--------------------------------------------------------
Sub Group2Me
/if (${Debugging}) /echo Sub Group2Me Entry
	/squelch /e3bcgz /nav id ${Me.ID}
/if (${Debugging}) /echo Sub Group2Me Exit
/return
|--------------------------------------------------------

|--------------------------------------------------------
| INIChange
|--------------------------------------------------------
Sub INIChange(Section,Key,Value)
/if (${Debugging}) /echo Sub INIChange Entry
	/ini "${IniFileName}" "${Section}" "${Key}" "${Value}"
/if (${Debugging}) /echo Sub INIChange Exit
/return
|--------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckStuck
| --------------------------------------------------------------------------------------------
Sub CheckStuck
	/if (${Debugging}) /echo Sub CheckStuck Entry
	/if (${Me.Stunned} || !${Navigation.Active}) /return
	/if (${StuckSpamTrigger}) /return
	|/echo ${Math.Distance[${OutY1},${OutX1}]}
	/if (${Math.Distance[${OutY1},${OutX1}]} < 20) {
		/varcalc StuckCountOut (${StuckCountOut})+1
		/if (${StuckCountOut}>6) /echo \arStuck ${StuckCountOut}
		/if (${Me.ActiveDisc.Name.Equal[Frenzied Resolve Discipline]}) /stopdisc
		/if (${StuckCountOut}>6) {
				|/call doorclick
				/if (${UseBeep}) {
					/beep
					/delay 1
					/beep
				}
				|/call doorclick
		}
		/varset StuckSpamTrigger 1
	} else {
		/varset StuckCountOut 0
	}
	/if (${StuckCountOut}>=8) {
				/message \ayThink I'm stuck... \agAttempting to get unstuck...
				/call Stuck
				/varset StuckCountOut 0
		}
	/if (${Debugging}) /echo Sub CheckStuck Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: Stuck
| --------------------------------------------------------------------------------------------
sub Stuck
/if (${Debugging}) /echo Sub Stuck Entry
/if (${StuckSwitch}) {
	/if (${Debugging}) /echo Hide Corpse STUCK
	/hidecorpse all
	/call BackUp
	/varset myTargetID 0
	/varset StuckSwitch 0
	/varset StuckCountOut 0
	} else {
		|/call DoorClick
		/varset StuckSwitch 1
		/varset StuckCountOut 0
		/varset courseCorrection 0
		/if (${Debugging}) /echo Hide Corpse STUCK
		/hidecorpse none
		}
/if (${Debugging}) /echo Sub Stuck Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: BackUp
| --------------------------------------------------------------------------------------------
Sub BackUp
	/if (${Debugging}) /echo Sub Backup Entry
    /declare strafedir string local
	/target clear
	|/call DoorClick
	/if (${Navigation.Active}) /nav pause
	/if (${Me.FeetWet}) {
		/keypress down hold
		/delay 10
		/keypress PAGE_UP hold
		/delay 20
		/keypress up hold
		/keypress right hold
		/delay 10
		/keypress left
		/keypress down
		/keypress PAGE_DOWN
	}
	/keypress back hold
	/delay 20
	/varset myTargetID 0
	/keypress back
	/if (${Math.Rand[2]}) {
		/varset strafedir STRAFE_LEFT
	} else {
		/varset strafedir STRAFE_RIGHT
	}
	/keypress ${strafedir} hold
	/delay 20
	/keypress ${strafedir}
	/delay 10
	/keypress forward hold
	/delay 10
	/keypress forward
	|/if (!${Navigation.Active}) /nav pause
	/if (${Debugging}) /echo Sub Backup Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: SetLoc
| --------------------------------------------------------------------------------------------
sub SetLoc
	/if (${Debugging}) /echo Sub SetLoc Entry
	/if (${StuckSpamTimerSet} || !${Navigation.Active}) /return
	/varset OutX1 ${Me.X}
    /varset OutY1 ${Me.Y}
	/varset StuckSpamTimerSet 5s
	|----------------------------------------------------------------
	|/echo (${Int[${Me.X}]}==${OutX1}) && (${Int[${Me.Y}]}==${OutY1})
	|----------------------------------------------------------------
	/if (${Debugging}) /echo Sub SetLoc Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GroupWait
| --------------------------------------------------------------------------------------------
Sub GroupWait
/if (${Debugging}) /echo Sub GroupWait Entry
:WaitForGroup
/if (${Me.XTarget}) {
	/if (${Navigation.Active}) /nav stop
	/call Group2Me
	/call DoClearTargets
	/goto :WaitForGroup
}
/message \ayWaiting for the group. . .

/if (${Debugging}) /echo ${Group.Member[1].CleanName}:(${Group.Member[1].Distance}) ${Group.Member[2].CleanName}:(${Group.Member[2].Distance}) ${Group.Member[3].CleanName}:(${Group.Member[3].Distance}) ${Group.Member[4].CleanName}:(${Group.Member[4].Distance}) ${Group.Member[5].CleanName}:(${Group.Member[5].Distance})

    /while ((${Group.Member[1].Distance} > 40) || (${Group.Member[2].Distance} > 40) || (${Group.Member[3].Distance} > 40) || (${Group.Member[4].Distance} > 40) || (${Group.Member[5].Distance} > 40) || (${Group.Member[6].Distance} > 40)) {
        /message \aywaiting for the group, timer ${GroupWaitTimer}.\ax
		/squelch /e3bcgz /stand
		/squelch /e3bcgz /nav id ${Me.ID}
        /delay 5s
		/varcalc GroupWaitTimer (${GroupWaitTimer})+1
		/call GroupWaitTimer
		/goto :WaitForGroup
	}
	/varset GroupWaitTimer 0
	/message \ay. . . my group is now here.\ax
	/if (${Debugging}) /echo Sub GroupWait Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GroupWaitTimer
| --------------------------------------------------------------------------------------------
Sub GroupWaitTimer
	/if (${Debugging}) /echo Sub GroupWaitTimer Entry
	/if (${GroupWaitTimer}==8) /varset GroupWaitTimer 0
	/if (${GroupWaitTimer}==5) {
		/message \ayA Group Member might be stuck!
		/squelch /e3bcgza /stand
		/squelch /e3bcgza /removelev
		/squelch /e3bcgza /moveto loc ${Me.Y} ${Me.X} ${Me.Z}
		/squelch /e3bcgza /keypress back hold
		/delay 3s
		/squelch /e3bcgza /keypress back
	}
	/if (${GroupWaitTimer}==6) {
		/message \ayA Group Member is stuck!
		/squelch /e3bcgza /moveto loc ${Me.Y} ${Me.X} ${Me.Z}
		/squelch /e3bcgza /keypress forward hold
		/delay 2s
		/squelch /e3bcgza /keypress forward
		/delay 2s
	}
	|--- Use Wayfarers Brotherhood Emblem' to COTH the group.
	/if (${GroupWaitTimer}==7 && ${FindItemCount[Wayfarers Brotherhood Emblem]}>0) {
		/message \ayA Group Member is stuck, Attempting to CoH !!!
		/delay 1s
		/coth group
		/delay 1s
		/call CheckCasting
		/delay 5
	}
	/if (${Debugging}) /echo Sub GroupWaitTimer Exit
/return GroupWaitTimer
|--------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckCasting
| --------------------------------------------------------------------------------------------
Sub CheckCasting
	/if (${Debugging}) /echo Sub CheckCasting Entry

	|-------------------------
	:CheckCastingNow
	/if (${Me.Casting.ID}) {
		/message \ag-- Waiting to stop casting.
		/delay 1s !${Me.Casting.ID}
		/goto :CheckCastingNow
		/message \ag-- I am done casting.
		/delay 1s
		/if (${Target.ID} && !${Bool[${Spawn[npc radius 35].Aggressive}]}) /squelch /target clear
	}
	|-------------------------
	
	/if (${Debugging}) /echo Sub CheckCasting Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GMCheck
| --------------------------------------------------------------------------------------------
Sub GMCheck
/if (${Debugging}) /echo Sub GMCheck Entry
/if (${Spawn[gm].ID} && ${AFKGM}) {
				/message \ar WARNING GM nearby!
				/if (${UseBeep}) /beep
				|------------------------------------------------
				/call GMMode
				|------------------------------------------------
				}
/if (${Debugging}) /echo Sub GMCheck Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GMMode
| --------------------------------------------------------------------------------------------
Sub GMMode
/if (${Debugging}) /echo Sub GMMode Entry
		/if (${UseBeep}) /beep
		/popcustom 13 5 Warning! GMMode: GM is Present!
		/message ==================================================================
		/message \ar***** GM IN ZONE, PAUUSING MACRO *****\ax
		/message ==================================================================
		/mqp

/if (${Debugging}) /echo Sub GMMode Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: ResetBard
| --------------------------------------------------------------------------------------------
Sub ResetBard
	/if (${Debugging}) /echo Sub ResetBard Entry
	/message \agPerforming Bard Reset !\ax

	/declare x 					int 	local	1

	|--- BRDMelodyName

	/for x 1 to ${Group.Members}
		/if (${Group.Member[${x}].Class.ShortName.Equal[BRD]}) {
		|-----------------------------------------
		/while (${Group.Member[${x}].OtherZone}) {
			:WaitForBardToZoneIn
				/message \ay - [\am${Group.Member[${x}].CleanName}\ay] is \arNOT IN ZONE\ax yet, waiting.
				/delay 3s
				/if (${Group.Member[${x}].OtherZone}) /goto :WaitForBardToZoneIn
		}
		|-----------------------------------------
		
		|-----------------------------------------
		/if (!${Defined[GrpBRDName]}) {
			/declare GrpBRDName string outer ${Group.Member[${x}].CleanName}
			
		} else {
			/varset GrpBRDName ${Group.Member[${x}].CleanName}
		}			
		|-----------------------------------------
		
		/message \ayResetting E3 [\atBRD\ay] MELODY for [\am${GrpBRDName}\ay].
		|------------------------
		|/squelch /e3bct ${Group.Member[${x}].CleanName} /mono E3
		/squelch /e3bct ${Group.Member[${x}].CleanName} /playmelody ${BRDMelodyName}
		/delay 3s
	}
	/next x

	/if (${Debugging}) /echo Sub ResetBard Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckGroupClasses
| --------------------------------------------------------------------------------------------
Sub CheckGroupClasses
	/if (${Debugging}) /echo Sub CheckGroupClasses Entry

	/declare i 					int 	local	0
	/declare targetClasses string local BRD,BER,BST,CLR,DRU,ENC,MAG,MNK,NEC,PAL,RNG,ROG,SHD,SHM,WAR,WIZ

	|--/message ==================================================================
	/message \ayChecking current Group Members \am(\atMe \ao+ \am[\at${Group.Members}\am])\ay against all classes.\ax
	|-- /message \ayClasses to be checked\ao:\ax
	|-- /message \am[\at${targetClasses}\am]\ax

	|---------------------------------------------------
	|---- CREATE DEFAULT CLASS VARIABLES FOR ALL CLASSES
	|---------------------------------------------------
    /for i 0 to ${Group.Members}
		
		|--/message ==================================================================
        |-- /message \ayChecking \am[\at${Group.Member[${i}].CleanName}\am]\ao: \am[\ay${Group.Member[${i}].Class.ShortName}\am] \awItemSelect- \am[\ay${Select[${Group.Member[${i}].Class.ShortName},${targetClasses}]}\am] 
		|------------
		/if (${Select[${Group.Member[${i}].Class.ShortName},${targetClasses}]}) {
            |-- /message Found a target class: \am[\ay${Group.Member[${i}].Class.ShortName}\am] - \am[\ay${Group.Member[${i}].CleanName}\am] \awin \am[\aytargetClasses\am]\ax.
			/if (!${Defined[GrpHas${Group.Member[${i}].Class.ShortName}Class]}) {
				|-- /message \ar--- \agMaking a \am[\atGrpHas${Group.Member[${i}].Class.ShortName}Class\am]\ag DECLARE for class \am[\at${Group.Member[${i}].Class.ShortName}\am]\ax
				/declare GrpHas${Group.Member[${i}].Class.ShortName}Class	bool	outer	TRUE
				
				|----------------------------------GrpBRDName
				/if (${Defined[GrpHasBRDClass]} && ${Group.Member[${i}].Class.ShortName.Equal[BRD]} && !${Defined[GrpBRDName]}) {
					/declare GrpBRDName string outer ${Group.Member[${i}].CleanName}				
				} else /if (${Defined[GrpHasBRDClass]} && ${Group.Member[${i}].Class.ShortName.Equal[BRD]} && ${Defined[GrpBRDName]}) {
					/varset GrpBRDName ${Group.Member[${i}].CleanName}
				}
				|----------------------------------GrpBRDName

				|----------------------------------GrpROGName
				/if (${Defined[GrpHasROGClass]} && ${Group.Member[${i}].Class.ShortName.Equal[ROG]} && !${Defined[GrpROGName]}) {
					/declare GrpROGName string outer ${Group.Member[${i}].CleanName}				
				} else /if (${Defined[GrpHasROGClass]} && ${Group.Member[${i}].Class.ShortName.Equal[ROG]} && !${Defined[GrpROGName]}) {
					/varset GrpROGName ${Group.Member[${i}].CleanName}
				}
				|----------------------------------GrpROGName
				
				|-- /message \ar--- Created\ao:\aw /declare GrpHas${Group.Member[${i}].Class.ShortName}Class	bool	outer	TRUE
			}
			/message \ay+ \agThe group has a \am[\ao${Group.Member[${i}].Class.ShortName}\am] - \am[\at${Group.Member[${i}].CleanName}\am]\ag.			
		}
		|------------
	/next i
    }
	
	|------------
	/if (${Defined[GrpHasBRDClass]} || ${Defined[GrpHasROGClass]}) {
		/message ==================================================================
		/if (${Defined[GrpHasBRDClass]} && ${Defined[GrpBRDName]}) /message \ay+ \agGroup \am[\aoBRD\am] \ayfor \aoINVIS\ay is set to - \am[\at${GrpBRDName}\am]\ag.
		/if (${Defined[GrpHasROGClass]} && ${Defined[GrpROGName]}) /message \ay+ \agGroup \am[\aoROG\am] \ayfor \aoCOH-SOS\ay is set to - \am[\at${GrpROGName}\am]\ag.	
	}	
	|------------
	
	/message ==================================================================
	|---------------------------------------------------
	|---- CREATE DEFAULT CLASS VARIABLES FOR ALL CLASSES
	|---------------------------------------------------	
	
	/if (${Debugging}) /echo Sub CheckGroupClasses Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckDriverPetStatus
| --------------------------------------------------------------------------------------------
Sub CheckDriverPetStatus
	/if (${Debugging}) /echo Sub CheckDriverPetStatus Entry

	|-----------------------------
	/if (${Select[${Me.Class.ShortName},PAL,SHD,WAR]} && ${Me.Pet.ID}) {
		/message ==================================================================
		/message \ay- I have a pet active.\ax
		|----------------------------------
		/if (${Select[${Me.Class.ShortName},PAL,WAR]}) {
			/message \ay- I can not suspend my pet, dismissing it.		
			/pet leave
			/delay 5
		}
		|----------------------------------
		/if (${Me.Class.ShortName.Equal[SHD]}) {
			/message \ay- Attempting to \am[\awSuspended Minion\am]\ay.\ax	
			|------------------------------
			/if (${Me.AltAbilityReady[Suspended Minion]}) {
				/squelch /alt act 176
				/call CheckCasting
				/delay 5
			} else {
				/message \ay- I can not suspend my pet, dismissing it.
				/pet leave			
				/delay 5
			}
			|------------------------------
		}
		|----------------------------------
		/message ==================================================================
	}
	|-----------------------------

	/if (${Debugging}) /echo Sub CheckDriverPetStatus Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckInvis
| --------------------------------------------------------------------------------------------
Sub CheckInvis
	/if (${Debugging}) /echo Sub CheckInvis Entry

	/declare y 					int 	local	0

	:CheckInvisNow
	|------------
	/if (!${Me.Combat} && !${Me.XTarget}) /call Group2Me
	|------------
		
	|-----------------------------	
	/for y 1 to ${Group.Members}
		|/echo Checking if ${Group.Member[${y}].CleanName} is close.
		/if (${Group.Member[${y}].Distance}>20) {			
			:MemberDistanceInvisCheck
			/message \ay- \am[\ag${Group.Member[${y}].CleanName}\am]\ay is \am[\ao${Group.Member[${y}].Distance}\am]\ay paces away still.
			|------------------------
			/delay 5 ${Group.Member[${y}].Distance}<20
			/if (${Group.Member[${y}].Distance}>20) /goto :MemberDistanceInvisCheck
			|------------------------
		}
	/next y
	|-----------------------------		
	
	|-----------------------------	
	| -- DELAY TO MAKE SURE GROUP STOPPED BEFORE ATTEMPTING TO CAST INVIS !
	|-----------------------------
	/delay 1s
	/for y 0 to ${Group.Members}
		|/echo Checking if ${Group.Member[${y}].CleanName} is Moving.
		/if (${Group.Member[${y}].Moving}) {
			/message \ay- \am[\ag${Group.Member[${y}].CleanName}\am]\ay is Moving.... waiting.
			:MemberMovingInvisCheck
			|------------------------
			/delay 5 !${Group.Member[${y}].Moving}
			/if (${Group.Member[${y}].Moving}) /goto :MemberMovingInvisCheck
			|------------------------
		}
	/next y
	|-----------------------------	
	| -- DELAY TO MAKE SURE GROUP STOPPED BEFORE ATTEMPTING TO CAST INVIS !
	|-----------------------------

	|----------------------------------------------------------------------------
	|--- REFERENCE ----
	|----------------------------------------------------------------------------
	|------------- INDIVIDUAL OR UNDEAD ---------------
	|/squelch /e3bcgz /alt act 1212 	; -- Group Perfected Invisibility to Undead  -- Cleric / Necromancer / Paladin / Shadowknight
	|/squelch /e3bcgz /alt act 280 		; -- Group Perfected Invisibility to Undead -- Magician / Enchanter / Wizard
	|/squelch /e3bcgz /alt act 231 		; -- Shauri's Sonorious Clouding -- Bard AA
	|/squelch /e3bcgz /alt act 531 		; -- Cloak of Shadows -- Necromancer / Shadow Knight
	|/squelch /e3bcgz /alt act 8301 	; -- Improved Natural Invisibility -- Beastlord
	|------------- GROUP ---------------
	|/squelch /e3bcgz /alt act 630 		; -- Group Silent Presence -- Shaman
	|/squelch /e3bcgz /alt act 518 		; -- Shared Camouflage -- Druid / Ranger
	|/squelch /e3bcgz /alt act 1210 	; -- Group Perfect Invisibility -- Magician / Enchanter / Wizard
	|----------------------------------------------------------------------------

	|----------------------- IF ME !INVIS
	/if (!${Me.Invis}) {
		/message \arNeed to make myself invisible!
		/message \ayAttempting to invis group using alternate abilities !
		|------------------------------------
		|------------- UNDEAD ---------------
		|/if (!${Me.Invis} && ${GrpHasENCClass}) /call DoGrpInvisByClass CLR 1212
		|/if (!${Me.Invis} && ${GrpHasPALClass}) /call DoGrpInvisByClass PAL 1212
		|/if (!${Me.Invis} && ${GrpHasNECClass}) /call DoGrpInvisByClass NEC 1212
		|/if (!${Me.Invis} && ${GrpHasSHDClass}) /call DoGrpInvisByClass SHD 1212
		|------------- UNDEAD ---------------
		|/if (!${Me.Invis} && ${GrpHasMAGClass}) /call DoGrpInvisByClass MAG 280
		|/if (!${Me.Invis} && ${GrpHasENCClass}) /call DoGrpInvisByClass ENC 280
		|/if (!${Me.Invis} && ${GrpHasWIZClass}) /call DoGrpInvisByClass WIZ 280
		|------------- GROUP ---------------
		/if (!${Me.Invis} && ${GrpHasSHMClass}) /call DoGrpInvisByClass SHM 630
		|------------- GROUP ---------------
		/if (!${Me.Invis} && ${GrpHasDRUClass}) /call DoGrpInvisByClass DRU 518
		/if (!${Me.Invis} && ${GrpHasRNGClass}) /call DoGrpInvisByClass RNG 518
		|------------- GROUP ---------------
		/if (!${Me.Invis} && ${GrpHasENCClass}) /call DoGrpInvisByClass ENC 1210
		/if (!${Me.Invis} && ${GrpHasMAGClass}) /call DoGrpInvisByClass MAG 1210		
		/if (!${Me.Invis} && ${GrpHasWIZClass}) /call DoGrpInvisByClass WIZ 1210
		|------------- INDIVIDUAL ---------------
		|/if (!${Me.Invis} && ${GrpHasBRDClass}) /call DoGrpInvisByClass BRD 231
		/if (!${Me.Invis} && ${GrpHasSHDClass}) /call DoGrpInvisByClass SHD 531
		/if (!${Me.Invis} && ${GrpHasNECClass}) /call DoGrpInvisByClass NEC 531
		/if (!${Me.Invis} && ${GrpHasBSTClass}) /call DoGrpInvisByClass BST 8301
		|------------------------------------
		/delay 3s ${Me.Invis}
	}
	|----------------------- IF ME !INVIS
				
	|----------------------- IF ME !INVIS
	/if (!${Me.Invis}) {
		/if (${GrpHasBRDClass}) {
			/message \arNeed to make myself invisible!
			/message \ayI am \arSTILL NOT\ay invised, making \am[\at${GrpBRDName}\am]\ay sing \am[\at${BRDTravelSong}\am]\ay.
			|------------------------
			/squelch /e3bct ${GrpBRDName} /playmelody stop
			/delay 1s
			/squelch /e3bct ${GrpBRDName} /memspell ${BRDTravelSongSlot} ${BRDTravelSong}
			/delay 3s
			:CheckBrdInvisNow
			/if (!${Me.Invis}) {
				/squelch /e3bct ${GrpBRDName} /cast ${BRDTravelSongSlot} ${BRDTravelSong}
				/delay 3s
				/message \agWaiting for invis to kick in .....
				/delay 5s ${Me.Invis}
				/goto :CheckBrdInvisNow
			} else {
				/varset y ${Group.Members}
			}
			|------------------------		
		}
		|-----------------------------
		/delay 3s ${Me.Invis}
	}
	|----------------------- IF ME !INVIS				
		
	|----------------------- IF ME !INVIS
	/if (!${Me.Invis}) {
			/message \arNeed to make myself invisible!
			/message \ayI am \arSTILL NOT\ay invised, attempting \atlast resort\ay !
			|-----------------------------
			/if (${Me.Class.ShortName.Equal[NEC]} || ${Me.Class.ShortName.Equal[SHD]}) {
				/if (${Me.AltAbility[Cloak of Shadows]}) {
					/alt act ${Me.AltAbility[Cloak of Shadows]}
				} else /if (${FindItemCount[Cloudy Potion]}) {
					/casting "Cloudy Potion|Item"
				} else /if (${Me.ItemReady[Circlet of Shadows]} && !${Me.Buff[Gather Shadows].ID}) {
					/useitem Circlet of Shadows
					/delay 1s
					/message \agActivating \ay[\apCirclet of Shadows\ay]
					/delay 1s !${Me.ItemReady[Circlet of Shadows]}
				} else /if (${FindItemCount[Cloudy Potion]}) {
					/casting "Cloudy Potion|Item"
				} else {
					/message \ayYou are out of \at[\apCloudy Potions\at]\ay. \agFighting my way through if a group member doesn't have invis!
				}
			} else /if (${Me.Class.ShortName.Equal[BRD]}) {
				/if (${Me.AltAbility[Shauri's Sonorous Clouding]}) {
					/alt act ${Me.AltAbility[Shauri's Sonorous Clouding]}
					/delay 5
					/removelev
				} else /if (${FindItemCount[Cloudy Potion]}) {
					/casting "Cloudy Potion|Item"
				} else {
					/message \ayYou are out of \at[\apCloudy Potions\at]\ay. \agFighting my way through if a group member doesn't have invis!
				}
			} else /if (${Me.Class.ShortName.Equal[MAG]} || ${Me.Class.ShortName.Equal[WIZ]} || ${Me.Class.ShortName.Equal[ENC]}) {
				/if (${Me.AltAbility[Perfected Invisibility]}) {
					/alt act ${Me.AltAbility[Perfected Invisibility]}
				} else /if (${Me.AltAbility[Group Perfected Invisibility]}) {
					/alt act ${Me.AltAbility[Group Perfected Invisibility]}
				} else /if (${FindItemCount[Cloudy Potion]}) {
					/casting "Cloudy Potion|Item"
				} else {
					/message \ayYou are out of \at[\apCloudy Potions\at]\ay. \agFighting my way through if a group member doesn't have invis!
				}
			} else /if (${Me.Class.ShortName.Equal[SHM]}) {
				/if (${Me.AltAbility[Spirit Walk]}) {
					/alt act ${Me.AltAbility[Spirit Walk]}
				} else /if (${FindItemCount[Cloudy Potion]}) {
					/casting "Cloudy Potion|Item"
				} else {
					/message \ayYou are out of \at[\apCloudy Potions\at]\ay. \agFighting my way through if a group member doesn't have invis!
				}
			} else /if (${Me.Class.ShortName.Equal[BST]}) {
				/if (${Me.AltAbility[Natural Invisibility]}) {
					/alt act ${Me.AltAbility[Natural Invisibility]}
				} else /if (${FindItemCount[Cloudy Potion]}) {
					/casting "Cloudy Potion|Item"
				} else {
					/message \ayYou are out of \at[\apCloudy Potions\at]\ay. \agFighting my way through if a group member doesn't have invis!
				}
			} else /if (${Me.Class.ShortName.Equal[RNG]} || ${Me.Class.ShortName.Equal[DRU]}) {
				/if (${Me.AltAbility[Camouflage]}) {
					/alt act ${Me.AltAbility[Camouflage]}
				} else /if (${FindItemCount[Cloudy Potion]}) {
					/casting "Cloudy Potion|Item"
				} else {
					/message \ayYou are out of \at[\apCloudy Potions\at]\ay. \agFighting my way through if a group member doesn't have invis!
				}
			} else /if (${Me.Class.ShortName.Equal[ROG]}) {
				/if (${Me.AbilityReady[Hide]}) {
				/doability "Hide"
				/delay 1s
				}
				/if (${Me.AbilityReady[Sneak]}) {
				/doability "Sneak"
				/delay 1s
				} else /if (${FindItemCount[Cloudy Potion]}) {
					/casting "Cloudy Potion|Item"
				} else {
					/message \ayYou are out of \at[\apCloudy Potions\at]\ay. \agFighting my way through if a group member doesn't have invis!
				}
			} else /if (${FindItemCount[Cloudy Potion]}) {
				/casting "Cloudy Potion|Item"
			}
			/delay 3s ${Me.Invis}
	}
	|----------------------- IF ME !INVIS
	
	/if (!${Me.Invis}) /goto :CheckInvisNow
	
	/if (${Debugging}) /echo Sub CheckInvis Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: DoGrpInvisByClass
| --------------------------------------------------------------------------------------------
Sub DoGrpInvisByClass(string InvisClassShortName, String GrpInvisAltAbilityID)
	/if (${Debugging}) /echo Sub DoGrpInvisByClass Entry
	
	/declare x 					int 	local	0

	|/echo Checking for class (${InvisClassShortName}) in group.
	|/echo If Found, use ability (${GrpInvisAltAbilityID}).
			
	|-----------------------------
	/for x 1 to ${Group.Members}
		|/echo Checking for class (${InvisClassShortName}): (${Group.Member[${x}].CleanName}) - ${Group.Member[${x}].Class.ShortName.Equal[${InvisClassShortName}]} - to use ability: (${GrpInvisAltAbilityID})
		/if (${Group.Member[${x}].Class.ShortName.Equal[${InvisClassShortName}]}) {
			/message \ay[\am${Group.Member[${x}].CleanName}\ay] is a [\at${InvisClassShortName}\ay], attempting to making them cast invis (\agAlt Ability \ay[\am${GrpInvisAltAbilityID}\ay]) !
			|------------------------			
			/if ((${GrpInvisAltAbilityID}==231) && (${Group.Member[1].Level}<91)) {
				/message \ay[\am${Group.Member[${x}].CleanName}\ay] is a [\at${InvisClassShortName}\ay], but can \arNOT\ay use (\agAlt Ability \ay[\am${GrpInvisAltAbilityID}\ay]) yet due to their level !
			} else {
				/squelch /e3bct ${Group.Member[${x}].CleanName} /target clear
				/delay 1s
				/squelch /e3bct ${Group.Member[${x}].CleanName} /alt act ${GrpInvisAltAbilityID}
			}						
			/delay 3s ${Me.Invis}			
			/if (${Me.Invis}) {
				/varset x ${Group.Members}
			}
			|------------------------
		} else {
			|/echo \ay[\am${Group.Member[${x}].CleanName}\ay] is NOT a [\at${InvisClassShortName}\ay].
		}
	/next x
	|-----------------------------

	/if (${Debugging}) /echo Sub DoGrpInvisByClass Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GroupDeathChk
| --------------------------------------------------------------------------------------------
Sub GroupDeathChk
	/if (${Debugging}) /echo Sub GroupDeathChk Entry
	|--- If ImDead
	/if (${Me.State.Equal[DEAD]}) {
		/message \arYOU~ have died! Waiting for YOU to get off your face.
		|----------
		/while (${Me.State.Equal[DEAD]} ) {
			/call GMCheck
			/beep
			/beep
			/beep
			/delay 30
		}
		|----------
	}
	|--- If ImDead
	/if (${Me.XTarget}) /return
	|--- If Group --
	/if (${Group}) {
		/declare i int local
		|----------------------------------
		/for i 1 to ${Group}
			| -- If GroupMember IsDead
			/if (${Group.Member[${i}].State.Equal[DEAD]} ) {
				/message ${Group.Member[${i}].Name} has died. Waiting for them to get off their face.
				|------   If No Target ID
				/if (!${Me.XTarget}) {
					|----------------------------------
					/while (${Group.Member[${i}].State.Equal[DEAD]} && !${Me.XTarget}) {
						/call GMCheck
						/if ((${Me.Standing}) && (!${Me.Casting.ID}) && (!${Me.Mount.ID})) /sit
						/beep
						/delay 30
					}
					/squelch /e3bcgz /stand
				}
				|------   If No Target ID
			}
			| -- If GroupMember IsDead
		/next i
		|----------------------------------
	}
	|--- If Group --

	/if (${Debugging}) /echo Sub GroupDeathChk Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GroupManaChk
| --------------------------------------------------------------------------------------------
Sub GroupManaChk
	/if (${Debugging}) /echo Sub GroupManaChk Entry
	/if (${Me.XTarget}) /return

	|------------------- If NoCombat
	/if (!${Me.Combat}) {
		|---
		|--- If Me LowMana
		/if ((${Me.PctMana} < ${MedAt} && !${Me.State.Equal[DEAD]} && !${Select[${Me.Class.ShortName},WAR,BER,ROG,MNK,BRD]}) || (${BardMed} && ${Me.PctMana} < ${MedAt} && !${Me.State.Equal[DEAD]} && ${Me.Class.ShortName.Equal[BRD]})) {
			/message \arYOU are low on mana!
			/call Group2Me
			|------   If No Target ID
			/if (!${Me.XTarget}) {
				|--------------------------------------
				/while ((${Me.PctMana} < ${MedTill} && !${Me.XTarget} && !${Me.State.Equal[DEAD]} && !${Select[${Me.Class.ShortName},WAR,BER,ROG,MNK,BRD]}) || (${BardMed} && ${Me.PctMana} < ${MedTill} && !${Me.XTarget} && !${Me.State.Equal[DEAD]} && ${Me.Class.ShortName.Equal[BRD]})) {
					/message \agYour \am[\atMana\am]\ag is currently at \am[\at${Me.PctMana}\am]\ag%, medding to \am[\at${MedTill}\am]\ag%.
					/call GMCheck
					/if (${Me.Standing} && !${Me.Casting.ID} && !${Me.Mount.ID} && !${Navigation.Active}) /sit
					/delay 6s
				}
                /squelch /e3bcgz /stand
			}
			|------   If No Target ID
		}
		|--- If Me LowMana
		|--- If Group --
		/if (${Group}) {
			/declare i int local
			|--------------------------------------
			/for i 1 to ${Group}
				|------   If Valid GroupMemeber
				/if ((${Group.Member[${i}].PctMana} < ${MedAt} && ${Group.Member[${i}].Class.CanCast} && !${Group.Member[${i}].State.Equal[DEAD]} && !${Select[${Group.Member[${i}].Class.ShortName},BRD,WAR,MNK,BER,ROG]}) || (${BardMed} && (${Group.Member[${i}].PctMana} < ${MedAt}) && !${Group.Member[${i}].State.Equal[DEAD]} && ${Group.Member[${i}].Class.ShortName.Equal[BRD]})) {
					/message \ar${Group.Member[${i}].Name} is low on mana!
					/call Group2Me
					|--------------
					| Make Them Sit
					|--------------
					/squelch /e3bct ${Group.Member[${i}].CleanName} /sit
					|----
					/call Refresh
					|------   If No Target ID
					/if (!${Me.XTarget}) {
						|--------------------------------------
						/while ((${Group.Member[${i}].PctMana} < ${MedTill} && ${Group.Member[${i}].Class.CanCast} && !${Me.XTarget} && !${Group.Member[${i}].State.Equal[DEAD]} && !${Select[${Group.Member[${i}].Class.ShortName},BRD,WAR,MNK,BER,ROG]}) || (${BardMed} && ${Group.Member[${i}].PctMana} < ${MedTill} && !${Me.XTarget} && !${Group.Member[${i}].State.Equal[DEAD]} && ${Group.Member[${i}].Class.ShortName.Equal[BRD]})) {
							/message \ag${Group.Member[${i}].CleanName}'s \am[\atMana\am]\ag is currently at \am[\at${Group.Member[${i}].PctMana}\am]\ag%, medding to \am[\at${MedTill}\am]\ag%.
							/call GMCheck
							/if (${Me.Standing} && !${Me.Casting.ID} && !${Me.Mount.ID} && !${Navigation.Active}) /sit
							/delay 3s
							|----------
							/if (${Group.Member[${i}].Standing}) {
								/delay 6s
								/squelch /e3bct ${Group.Member[${i}].CleanName} /sit
							}
							|----------
						}
						/squelch /e3bcgz /stand
					}
					|------   If No Target ID
				}
				|------   If Valid GroupMemeber
			/next i
			|--------------------------------------
		}
		|--- If Group --
	}
	|------------------- If NoCombat

	/if (${Debugging}) /echo Sub GroupManaChk Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GroupEndChk
| --------------------------------------------------------------------------------------------
Sub GroupEndChk
	/if (${Debugging}) /echo Sub GroupEndChk Entry
	/if (${Me.XTarget}) /return

	|------------------- If NoCombat
	/if (!${Me.Combat}) {
		|---
		|--- If Me LowEnd
		/if ((${Me.PctEndurance} < ${MedEndAt} && !${Me.State.Equal[DEAD]} && ${Me.Class.ShortName.NotEqual[BRD]}) || (${BardMed} && ${Me.PctEndurance} < ${MedEndAt} && !${Me.State.Equal[DEAD]} && ${Me.Class.ShortName.Equal[BRD]})) {
			/message \arYOU are low on Endurance!
			/call Group2Me
			|------   If No Target ID
			/if (!${Me.XTarget}) {
				|--------------------------------------
				/while ((${Me.PctEndurance} < ${MedEndTill} && !${Me.XTarget} && !${Me.State.Equal[DEAD]} && ${Me.Class.ShortName.NotEqual[BRD]}) || (${BardMed} && ${Me.PctEndurance} < ${MedEndAt} && !${Me.State.Equal[DEAD]} && ${Me.Class.ShortName.Equal[BRD]})) {
					/message \agYour \am[\atEndurance\am]\ag is currently at \am[\at${Me.PctEndurance}\am]\ag%, medding to \am[\at${MedEndTill}\am]\ag%.
					/call GMCheck
					/if (${Me.Standing} && !${Me.Casting.ID} && !${Me.Mount.ID} && !${Navigation.Active}) /sit
					/delay 6s
				}
                /squelch /e3bcgz /stand
			}
			|------   If No Target ID
		}
		|--- If Me LowEnd
		|--- If Group --
		/if (${Group}) {
			/declare i int local
			|--------------------------------------
			/for i 1 to ${Group}
				|------   If Valid GroupMemeber
				/if (${Group.Member[${i}].ID}) {
					|------   If GroupMember LowEnd
					/if ((${Group.Member[${i}].PctEndurance} < ${MedEndAt} && !${Group.Member[${i}].State.Equal[DEAD]} && ${Group.Member[${i}].Class.ShortName.NotEqual[BRD]}) || (${BardMed} && ${Group.Member[${i}].PctEndurance} < ${MedEndAt} && !${Group.Member[${i}].State.Equal[DEAD]} && ${Group.Member[${i}].Class.ShortName.Equal[BRD]})) {
						/message \ar${Group.Member[${i}].Name} is low on Endurance!
						/call Group2Me
						|--------------
						| Make Them Sit
						|--------------
						/squelch /e3bct ${Group.Member[${i}].CleanName} /sit
						/call Refresh
						|------   If No Target ID
						/if (!${Me.XTarget}) {
							|---------------------------------------
							/while ((${Group.Member[${i}].PctEndurance} < ${MedEndTill} && !${Me.XTarget} && !${Group.Member[${i}].State.Equal[DEAD]} && ${Group.Member[${i}].Class.ShortName.NotEqual[BRD]}) || (${BardMed} && ${Group.Member[${i}].PctEndurance} < ${MedEndTill} && !${Me.XTarget} && !${Group.Member[${i}].State.Equal[DEAD]} && ${Group.Member[${i}].Class.ShortName.Equal[BRD]})) {
								/message \ag${Group.Member[${i}].CleanName}'s \am[\atEndurance\am]\ag is currently at \am[\at${Group.Member[${i}].PctEndurance}\am]\ag%, medding to \am[\at${MedEndTill}\am]\ag%.
								/call GMCheck
								/if (${Me.Standing} && !${Me.Casting.ID} && !${Me.Mount.ID} && !${Navigation.Active}) /sit
								/delay 3s
								|----------
								/if (${Group.Member[${i}].Standing}) {
									/delay 6s
									/squelch /e3bct ${Group.Member[${i}].CleanName} /sit
								}
								|----------
						}
						|---------------------------------------
						/squelch /e3bcgz /stand
						}
						|------   If No Target ID
					}
					|------   If GroupMember LowEnd
				}
				|------   If Valid GroupMemeber
			/next i
			|--------------------------------------
		}
		|--- If Group --
	}
	|------------------- If NoCombat

	/if (${Debugging}) /echo Sub GroupEndChk Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: Refresh
| --------------------------------------------------------------------------------------------
Sub Refresh
/if (${Debugging}) /echo Sub Refresh Entry
/if (${Debugging}) /echo Calling Refresh
	/keypress F2
	/delay 2s
	/keypress F3
	/delay 2s
	/keypress F4
	/delay 2s
	/keypress F5
	/delay 2s
	/keypress F6
	/delay 2s
	/squelch /target clear
	/if (${Debugging}) /echo Sub Refresh Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: GetExpeditionData
| --------------------------------------------------------------------------------------------
Sub GetExpeditionData
	/if (${Debugging}) /echo Sub GetExpeditionData Entry
		|--------------------------------------------
		:OpenDynamicZoneWindow
		|--- open the Expedition Window to pull data
		/keypress alt+z
		/delay 1s
		/delay 3s ${Window[DynamicZoneWnd].Open}
		/if (!${Window[DynamicZoneWnd].Open}) /goto :OpenDynamicZoneWindow
		|--------------------------------------------------------------
		|-- Determine if I have a Dranik Catacombs Expedition Assigned.
		|--------------------------------------------------------------
		/varset CurrentExpedition ${Window[DynamicZoneWnd].Child[DZ_CurrentDZValue].Text}
		|--------------------------
		/if (!${CurrentExpedition.Length}==0 && ${CurrentExpedition.Find[Catacombs of Dranik]}) {
			/varset DranikCExpedition 1
		} else {
			/varset DranikCExpedition 0
		}
		|--------------------------
		/keypress alt+z
		|--------------------------------------------
	/if (${Debugging}) /echo Sub GetExpeditionData Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckInADungeon
| --------------------------------------------------------------------------------------------
Sub CheckInADungeon
	/if (${Debugging}) /echo Sub CheckInADungeon Entry
	/if (${Select[${Zone.ID},330]}) {
		/varset InADungeon 1
	} else {
		/varset InADungeon 0
	}
	/if (${Debugging}) /echo Sub CheckInADungeon Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckHaveDranikCExpedition
| --------------------------------------------------------------------------------------------
Sub CheckHaveDranikCExpedition
	/if (${Debugging}) /echo Sub CheckHaveDranikCExpedition Entry

	|--------------------------------------------------------------
	|-- Determine if I have a Dranik Catacombs Expedition Assigned.
	|--------------------------------------------------------------
	/varset CurrentExpedition ${Window[DynamicZoneWnd].Child[DZ_CurrentDZValue].Text}
	|--------------------------
	/if (!${CurrentExpedition.Length}==0 && ${CurrentExpedition.Find[Catacombs of Dranik]}) {
		/varset DranikCExpedition 1
	} else {
		/varset DranikCExpedition 0
	}
	|--------------------------

	/if (${Debugging}) /echo Sub CheckHaveDranikCExpedition Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckINI
| --------------------------------------------------------------------------------------------
Sub CheckINI(string IniName,string Section,string Key,string TypeVar,Default)
    /if (${Debugging}) /echo (IniName:${IniName} Section:${Section} Key:${Key} TypeVar:${TypeVar})
	/if (${Debugging}) /echo Sub CheckINI Entry
	/if (!${Ini[${IniName},${Section},${Key}].Length}) {
		/ini ${IniName} ${Section} ${Key} ${Default}
	}
	/declare ${Key} ${TypeVar} outer ${Ini[${IniName},${Section},${Key}]}
	/message \atLoading \ayINI \ay[\am${IniName}\ay] \ar~ \aoKey: \ag${Key} \aoType: \ag${TypeVar} \aoINI Value: \at\ay[\am${Ini[${IniName},${Section},${Key}]}\ay]
	/if (${Debugging}) /echo Sub CheckINI Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckThings
| --------------------------------------------------------------------------------------------
Sub CheckThings
	/if (${Debugging}) /echo Sub CheckThings Entry
	
	/message \ayChecking running status of \am[\atxfix.lua\am]\ao:\ax

	|--------
	/if (!${Lua.Script[xfix].Status.Equal[Running]}) {
		/message \atTrying to start xfix.lua...\ax
		/lua run xfix
		/delay 2s
	}
	|--------

	|--------
	/if (!${Lua.Script[xfix].Status.Equal[Running]}) {
		/message \arxfix.lua can not be started, and it IS needed, exiting !\ax
		/message ==================================================================
		/end
	} else {
		/message \agxfix is already active.
		/message ==================================================================
	}
	|--------
	
	|-----------------------
	|-- SEET GROUP ROLES ---
	|-----------------------
	/message \aySetting group role(s)\ao:\ax.
	/message \ayMaking myself \am[\atMain Tank\am]\ay.
	/grouproles set ${Me.CleanName} 1
	/delay 5
	/message \ayMaking myself \am[\atMain Assist\am]\ay.
	/grouproles set ${Me.CleanName} 2
	/delay 5
	/message ==================================================================
	/delay 2s
	|-----------------------
	
	|---------------------------------
	| Plugin check - Enabble / disable
	|---------------------------------
	|---------
	/if (${Bool[${Plugin[MQ2Bucles]}]}) {
        /squelch /plugin MQ2Bucles unload noauto
        /message MQ2Bucles detected! This macro doesn't like it! Unloading temporarily ...
    }
	|---------
	/call CheckPlugin MQ2Nav
	/call CheckMesh
	/call CheckPlugin MQ2Events	
	/call CheckPlugin MQ2MoveUtils
	|---------------------------------
	
	|-------------------------
	|-- CHECK DRIVER PET STATUS
	|-------------------------
	/call CheckDriverPetStatus
	|-------------------------	

	|-------------------------	
	| Looting Selection Setup
	|-------------------------		
	/if (${LootCorpse}) {		
		/message ==================================================================
		/message \ay--- \atENABLING\ax \am${MacroName}\ax LOOTING, WE WILL LOOT CORPSE(S).
		/message ==================================================================		
		/if (${LootMethod.Equal[DCONLY]}) {
			/squelch /lootoff
			/message \ay--- \agLOOTING METHOD:\ax (\am${LootMethod}\ax) we will only loot\ax
			/message \ay    [\atDiamond Coin\ay] and [\arHIGH VALUE ITEMS\ay]\ay.\ax
			|------------------------------------------------
			|--------------
			/if (${LootTradeMats}) {
				/message \ay--- \ag Loot Tradeskill Materials set to [TRUE]
			} else {
				/message \ay--- \ar Loot Tradeskill Materials set to [FALSE]
			}
			|--------------
			/message \ag--- Seting up \am[\aoDRANIK LOOT ARRAY\am] \ag- \am[\at${DranikCLootArray.Size}\am]\ag - items for \am[\aoDCONLY\am]\ag. 
			/call DranikCLootArraySetup			
		}  
		/if (${LootMethod.Equal[E3]}) {
			/squelch /looton
			/message \ay--- \agLOOTING METHOD:\ax (\am${LootMethod}\ax) we will only loot according to \am${LootMethod}\ax settings.
			/message \ay    [ If configured in your \am${LootMethod}\ax config files. \ag("Loot Settings.ini")\ax ]
		}
		
		/if (${LootMethod.Equal[TURBOLOOT]}) {
			/squelch /lootoff
			/message \ay--- \agLOOTING METHOD:\ax (\am${LootMethod}\ax) we will only loot according to \am${LootMethod}\ax settings.
			/message \ay    [ If configured in your \am${LootMethod}\ax config files. \ag(turboloot.ini)\ax ]
			|-------------
			/if (${TurboLooter.Equal[NOBODY]} || ${TurboLooter.Equal[NULL]} || ${TurboLooter.Equal[${Me.CleanName}]}) {
				/message ==================================================================
				/message \ar    WARNING\ao: \arYOU CAN NOT HAVE TURBOLOOTER SET AS \ar[\at${TurboLooter}\am]\ar.
				/message \ar    It can not be NOBODY or YOURSELF ! \ag ~ FIX AND RESTART ~.\ax
				/message ==================================================================
				/end
			}			
			|-------------
			/message \ay    [ Looter cuurently set to: \am[\at${TurboLooter}\am]\ay   ]			
		}		
		/message ==================================================================
		/delay 3s
	} else {
		/squelch /lootoff
		/message ==================================================================
		/message \ar--- DISABLING \am${MacroName}\ar LOOTING, YOU WILL NOT LOOT CORPSE(S)!
		/message ==================================================================
		/delay 3s
	}
	|-------------------------	

	|-------------------------
	|-- CHECK CLASSES SET VARS
	|-------------------------
	/call CheckGroupClasses
	|-------------------------
	
	|-------------------------
	| Delay to read output.
	|-------------------------
	/delay 3s
	|-------------------------
	
	/if (${Endmac}) /end
	/if (${Debugging}) /echo Sub CheckThings Exit

/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckMesh  ( Called from CheckThings )
| --------------------------------------------------------------------------------------------
Sub CheckMesh
	/if (${Debugging}) /echo Sub CheckMesh Entry
	/if (!${Navigation.MeshLoaded}) {
		/nav reload
		/delay 3s ${Navigation.MeshLoaded}
		/if (!${Navigation.MeshLoaded}) {
			/message \arNo navigational mesh could be found for this zone. Make one and try again.
			/varset Endmac TRUE
		}
	}
	/if (${Debugging}) /echo Sub CheckMesh Exit
/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SUB: CheckPlugin
| --------------------------------------------------------------------------------------------
  Sub CheckPlugin(string pluginname)
  /if (${Debugging}) /echo Sub CheckPlugin Entry

	|------------
	/if (!${Bool[${Plugin[${pluginname}]}]} && !${pluginname.Equal[E3BCS]}) {
		/message \ag${pluginname}\ax \arNOT\ax detected! This macro requires it! Loading ...
		/squelch /plugin ${pluginname}
		/if (!${Bool[${Plugin[${pluginname}]}]}) {
			/message \ag${pluginname}\ax \arSTILL NOT\ax detected! This macro requires it! EXITING ...
			/endmacro
		} else {
		    /message \ag${pluginname}\ax \atNOW\ax detected !
		}
	} else {
		/message \ag${pluginname}\ax detected!
	}
	|------------

	/if (${Debugging}) /echo Sub CheckPlugin Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: AutoSell_Loot_SupplyAgent
| --------------------------------------------------------------------------------------------
  Sub AutoSell_Loot_SupplyAgent
  /if (${Debugging}) /echo Sub AutoSell_Loot_SupplyAgent Entry

	/declare MerchName	string	local Merchant

	/message \aw<\ar$\ao$\ay$\ag$\at$\au$\am$\ap$\aw> \agAttempting to locate a \ay[\at${MerchName}\ay]\ag to \ay[\atAutoSell\ay]\ag ! \aw<\ap$\am$\au$\at$\ag$\ay$\ao$\ar$\aw>
	/target clear
	/delay 2s !${Target.ID}

	/squelch /target ${MerchName}
	/delay 2s ${Target.ID}

	|-------------------------------------
	/if (${Target.ID}) {
		/squelch /nav id ${Target.ID}
		/delay 5
		/while (${Navigation.Active}) {
			/call SetLoc
			/call CheckStuck
			/delay 5
		}
	}
	/delay 5
	|-------------------------------------

	|------------------
	/if (${ReclaimDC}) /call ReclaimAltDC
	|------------------

	|-------------------------------------
	/if (${Target.ID} && ${Target.Distance}<=20) {
		/nomodkey /click right target
		/delay 5s ${Window[MerchantWnd].Open}
		/message \ay Attempting to \amAutoSell\ax now.
		/delay 1s
		/call OpenPacks
		/delay 1s
		/autosell
		|-----------------
		/while (${Window[MerchantWnd].Open}) {
			/delay 5
		}
		|-----------------
		/call ClosePacks
		/delay 1s
	}
	|-------------------------------------

	/message \aw<\ar$\ao$\ay$\ag$\at$\au$\am$\ap$\aw> \agDone Selling! \ag \aw<\ap$\am$\au$\at$\ag$\ay$\ao$\ar$\aw>

	/if (${Debugging}) /echo Sub AutoSell_Loot_SupplyAgent Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: AutoSell_Loot
| --------------------------------------------------------------------------------------------
  Sub AutoSell_Loot
  /if (${Debugging}) /echo Sub AutoSell_Loot Entry

  	|--------------------------
	/message \am<***> Sending the rest of my group to Magus as I sell <***>
  	/squelch /e3bcgz /tar Magus Alaria
	/delay 5
	/squelch /e3bcgz /nav target
	/delay 5
	|--------------------------

	/declare MerchName	string	local Merabo

	/message \aw<\ar$\ao$\ay$\ag$\at$\au$\am$\ap$\aw> \agAttempting to locate a \ay[\at${MerchName}\ay]\ag to \ay[\atAutoSell\ay]\ag ! \aw<\ap$\am$\au$\at$\ag$\ay$\ao$\ar$\aw>
	/target clear
	/delay 2s !${Target.ID}

	/squelch /target ${MerchName}
	/delay 2s ${Target.ID}

	|-------------------------------------
	/if (${Target.ID}) {
		/squelch /nav id ${Target.ID}
		/delay 5
		/while (${Navigation.Active}) {
			/call SetLoc
			/call CheckStuck
			/delay 5
		}
	}
	/delay 5
	|-------------------------------------

	|------------------
	/if (${ReclaimDC}) /call ReclaimAltDC
	|------------------

	|-------------------------------------
	/if (${Target.ID} && ${Target.Distance}<=20) {
		/nomodkey /click right target
		/delay 5s ${Window[MerchantWnd].Open}
		/message \ay Attempting to \amAutoSell\ax now.
		/delay 1s
		/call OpenPacks
		/delay 1s
		/autosell
		|-----------------
		/while (${Window[MerchantWnd].Open}) {
			/delay 5
		}
		|-----------------
		/call ClosePacks
		/delay 1s
	}
	|-------------------------------------

	/message \aw<\ar$\ao$\ay$\ag$\at$\au$\am$\ap$\aw> \agDone Selling! \ag \aw<\ap$\am$\au$\at$\ag$\ay$\ao$\ar$\aw>

	/if (${Debugging}) /echo Sub AutoSell_Loot Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: ReclaimAltDC
| --------------------------------------------------------------------------------------------
Sub ReclaimAltDC
 /if (${Debugging}) /echo Sub ReclaimAltDC Entry

	/varset CurrentDC ${FindItemCount[=Diamond Coin]}
	/varset CurrentDCAC ${Me.AltCurrency[20]}
	/message \ayDiamond Coin: Alternate Currency=(\at${CurrentDCAC}\ay) | Inventory=(\at${CurrentDC}\ax)

	|-----------------------------------------------
	/if (${CurrentDC}>0) {
		; --- If I have DC in inventory, RECLAIM it to Alternate Currency !!!
		/message \ag$$$\ay I have [\atDiamond Coin\ay]  to reclaim!\ax

		; Open the Inventory Window if it is closed
		|----------------------------------------------
		/if (!${Window[InventoryWindow].Open}) /call OpenInvWindow
		|----------------------------------------------

		; Select Alt Currency Tab
		/if (${Debugging}) /echo Selecting Alt Currency Tab
		/if (!${Window[InventoryWindow].Child[IW_AltCurrPage].Open})  /notify InventoryWindow IW_Subwindows tabselect 5
		/delay 5

		; Select Diamond Coin off the Alternate Currecy tab in Inventory window ..  YOU NEED TO OPEN INVENTORY WINDOW FOR THIS !
		/if (${Debugging}) /echo Selecting Diamond Coins
		/notify InventoryWindow IW_AltCurr_PointList listselect 2
		/delay 5

		; Click the RECLAIM BUTTON after selecting Diamond Coin previously
		/nomodkey /notify InventoryWindow AltCurr_ReclaimButton LeftMouseUp
		/delay 5
	} else {
	    ; --- If I have NO DC in inventory to RECLAIM
		/message \ag$$$\ay I have \arNO\ay [\atDiamond Coin\ay] to reclaim!\ax
	}
	|-----------------------------------------------
	; Update the DC and Alternate DC Currency ammount.
	/varset CurrentDC ${FindItemCount[=Diamond Coin]}
	/varset CurrentDCAC ${Me.AltCurrency[20]}
	/message \ayDiamond Coin: Alternate Currency=(\at${CurrentDCAC}\ay) | Inventory=(\at${CurrentDC}\ax)
	; Close the Inventory Window if it is open
	|----------------------------------------------
	/if (${Window[InventoryWindow].Open}) /call CloseInvWindow
	|----------------------------------------------

	/if (${CurrentDC}==0) /message \ag$$$ \ayAll available DC was converted to Alternate Currency !

/if (${Debugging}) /echo Sub ReclaimAltDC Exit

/return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: OpenInvWindow
| --------------------------------------------------------------------------------------------
  Sub OpenInvWindow
 /if (${Debugging}) /echo Sub OpenInvWindow Entry
	/if (!${Window[InventoryWindow].Open}) {
	:OpenInventoryWindow
		/nomodkey /keypress inventory
		/delay 5
		/if (${Window[InventoryWindow].Open}) /message Inventory Window (Open).
		/if (!${Window[InventoryWindow].Open}) /goto :OpenInventoryWindow
	}
 /if (${Debugging}) /echo Sub OpenInvWindow Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: CloseInvWindow
| --------------------------------------------------------------------------------------------
  Sub CloseInvWindow
  /if (${Debugging}) /echo Sub CloseInvWindow Entry

	/if (${Window[InventoryWindow].Open}) {
	:CloseInventoryWindow
		/nomodkey /keypress inventory
		/delay 5
		/if (!${Window[InventoryWindow].Open}) /message Inventory Window (Closed).
		/if (${Window[InventoryWindow].Open}) /goto :CloseInventoryWindow
	}

  /if (${Debugging}) /echo Sub CloseInvWindow Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: CheckIfBagsFull
| --------------------------------------------------------------------------------------------
  Sub CheckIfBagsFull
  /if (${Debugging}) /echo Sub CheckIfBagsFull Entry

  |--------------------------------------------
  /if (${BagsAreFull}) {
		|--------------------------------------------
		/if (${Me.AltAbilityReady[Summon Resupply Agent]}) {
			/message ==================================================================
			/message \ar +++ Your bags are full summoning a \ay[\atResupply Agent\ay]\ar to AutoSell.\ax
			/message ==================================================================
			/alt act ${Me.AltAbility[Summon Resupply Agent].ID}
			/delay 2s
			/call AutoSell_Loot_SupplyAgent
			/delay 1s
		} else {
			message ==================================================================
			/message \ar +++ Your bags are full and you can not summon a \ay[\atResupply Agent\ay]\ar to AutoSell.\ax
			/message \ar --- DISABLING ${MacroName} LOOTING, YOU WILL NOT LOOT CORPSES !
			/message ==================================================================
			/squelch /lootoff
		}
		|--------------------------------------------
		/varset BagsAreFull FALSE
		|--------------------------------------------
  }
  |--------------------------------------------

  /if (${Debugging}) /echo Sub CheckIfBagsFull Exit
  /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
|SUB: Rogue_SOS_COH
| --------------------------------------------------------------------------------------------
  Sub Rogue_SOS_COH
  /if (${Debugging}) /echo Sub Rogue_SOS_COH Entry
  
	|-----------------------------
	/if (${GrpHasROGClass} && ${Defined[GrpROGName]}) {
			/message \ay[\am${GrpROGName}\ay] is a [\atROG\ay], making them run to safespot and COH us!
			|---------------------------
			/squelch /e3bct ${GrpROGName} /macro GoSOS.mac "2098.09 274.34 -135.09" ${Me.CleanName} ${Macro.Name}
			/delay 1s
			/message ==================================================================
			/message \arPAUSING ${Macro.Name} UNTIL ROGUE SOS COH COMPLETE !\ax
			|---------------------------
	
			|---------------------------
			|--- SET the Cycle Loop TRUE
			|---------------------------			
			/call IniChange "Theme" "CompletedPathTo" "TRUE"
			/message \atUpdating (\ay${IniFileName})\ax INI file with PathTo completion.\ax
			/call ForceSpawnStepReset
			/message ==================================================================
			/mqp
			|------------------------

	}
	|-----------------------------

  /if (${Debugging}) /echo Sub Rogue_SOS_COH Exit
 /return
| --------------------------------------------------------------------------------------------

| --------------------------------------------------------------------------------------------
| SECTION: -- Events   --   START
| --------------------------------------------------------------------------------------------
|--------------------------------------------------------
Sub Event_Catacomb_A
	/message \ayYou have received an expedition for \am[\atCatacombs of Dranik (Azia)\am]\ar - BOO - Leaving !\ax
	/squelch /e3bcgza /dzquit
	/delay 1s
	/varset DranikCExpedition 0
	/varset CurrentExpedition NULL
	/delay 1s
	|/echo DranikCExpedition=(${DranikCExpedition}) | CurrentExpedition=(${CurrentExpedition})
	/message \ar - WRONG EXPEDITION !
	/say catacombs
	/doevents flush Catacomb_A
/return
|--------------------------------------------------------
|--------------------------------------------------------
Sub Event_Catacomb_B
	/message \ayYou have received an expedition for \am[\atCatacombs of Dranik (Beza)\am]\ar - BOO - Leaving !\ax
	/squelch /e3bcgza /dzquit
	/delay 1s
	/varset DranikCExpedition 0
	/varset CurrentExpedition NULL
	/delay 1s
	|/echo DranikCExpedition=(${DranikCExpedition}) | CurrentExpedition=(${CurrentExpedition})
	/message \ar - WRONG EXPEDITION !
	/say catacombs
	/doevents flush Catacomb_B
/return
|--------------------------------------------------------
|--------------------------------------------------------
Sub Event_Catacomb_C
	/message \ayYou have received an expedition for \am[\atCatacombs of Dranik (Caza)\am]\ag - WOOT WOOT WOOT !\ax
	/varset DranikCExpedition 1
	/varset CurrentExpedition ${Window[DynamicZoneWnd].Child[DZ_CurrentDZValue].Text}
	/delay 1s
	|/echo DranikCExpedition=(${DranikCExpedition}) | CurrentExpedition=(${CurrentExpedition})
	/message \ag + CORRECT EXPEDITION !
	/doevents flush Catacomb_C
/return
|--------------------------------------------------------
|--------------------------------------------------------
Sub Event_Cannot_See
	/stick off
	/delay 30
	/squelch /call WaitNav ${Target}
	/delay 5
	/stick
	/doevents flush Cannot_See
/return
|--------------------------------------------------------
|--------------------------------------------------------
Sub Event_Cant_Hit
	/stick off
	/delay 30
	/squelch /call WaitNav ${Target}
	/delay 5
	/stick
	/doevents flush Cant_Hit
/return
|--------------------------------------------------------
|--------------------------------------------------------
Sub Event_Too_Far
	/stick off
	/delay 30
	/squelch /call WaitNav ${Target}
	/delay 5
	/stick
	/doevents flush Too_Far
/return
|--------------------------------------------------------
|--------------------------------------------------------
  Sub Event_NavMeshReload
	/message \agReloading navmesh for zone: \ay(\am${Zone.Name}\ay)\ag on all toons.
	/squelch /e3bcgza /nav reload
	/call BackUp
	/delay 1s
    /doevents flush NavMeshReload
  /return  
|-------------------------------------------------------- 
|--------------------------------------------------------
Sub Event_TurboLootDone
	/message \at+ \am[\ag${TurboLooter}\am]\ay has finished looting.
	/varset TurboLootPause FALSE
	/doevents flush TurboLootDone
/return
|-------------------------------------------------------
|--------------------------------------------------------
Sub Event_BagsFull
	/varset BagsAreFull TRUE
	/doevents flush BagsFull
/return
|--------------------------------------------------------
| --------------------------------------------------------------------------------------------
| SECTION: -- Events   --   END
| --------------------------------------------------------------------------------------------
